

##  hook

### pre-commit


[source,shell]
----
----


## gitigore

[source,shell]
----
# 排除任何 层级的 "lib/"
lib/
# 但保留这个 lib 目录
!some/commit/lib/
----


## 开发模式

link:https://bbs.huaweicloud.com/blogs/281789[Git工作流中常见的三种分支策略：GitFlow、GitHubFlow以及GitLabFlow]
默认主干: master

* branch: 分支模式, 多个代码分支自动集成发布
* develop: 自由模式: 可使用任意项目分支进行构建发布

* Git Flow: 项目分支合并到集成分支, 基于集成分支发布
** Master分支: 主干分支，也是正式发布版本的分支，其包含可以部署到生产环境中的代码，通常情况下只允许其他分支将代码合入，不允许向Master分支直接提交代码（对应生产环境）。
*** create from : 无
*** merge from : hotfix,  develop

** Develop分支：开发分支，用来集成测试最新合入的开发成果，包含要发布到下一个Release的代码（对应开发环境）。
*** create from: master, hotfix,
*** merge from : feature

** Feature分支：特性分支，通常从Develop分支拉出，每个新特性的开发对应一个特性分支，用于开发人员提交代码并进行自测。自测完成后，会将Feature分支的代码合并至Develop分支，进入下一个Release。
*** create from: develop
*** merge from : any

** Release分支：发布分支，发布新版本时，基于Develop分支创建，发布完成后，合并到Master和Develop分支（对应集成测试环境）。
*** create from: develop
*** merge from : 无

** Hot fix分支：热修复分支，生产环境发现新Bug时创建的临时分支，问题验证通过后，合并到Master和Develop分支。



## 远程仓库复制
[source,shell]
----
# clone 新仓库
git clone git@xxx-host.com:/xxx-group/xxx-repo2.git
cd xxx-repo1

# 强制推送到新远程
git remote add tmp git@xxx-host.com:/xxx-group/xxx-repo1.git
git fetch tmp
git push -f origin tmp/master:master

# 清理
git remote remove tmp
----

== 远程仓库复制:子目录
link:https://grantwinney.com/how-to-move-a-subdirectory-of-one-repo-into-its-own-repository/[Move a subdirectory into its own Git repo, with history]
=== 方式1： 使用 git-filter-repo

== filter-branch
[source,shell]
----
cd ${your_git_repo}
FILTER_BRANCH_SQUELCH_WARNING=1
git filter-branch --subdirectory-filter the-sub-directory-to-keep
----


=== 方式2： 使用三方工具 git-filter-repo

- link:https://github.com/newren/git-filter-repo[git-filter-repo]
- link:https://www.mankier.com/1/git-filter-repo[git-filter-repo - Man Page]

[source,shell]
----
# 前提：已经安装了 git 和 python3
# 下载到 PATH 环境变量中一个子目录，并添加可执行权限
wget -O ${HOME}/git-filter-repo https://raw.githubusercontent.com/newren/git-filter-repo/refs/heads/main/git-filter-repo
chmod u+x ${HOME}/git-filter-repo

cd ${your_git_repo}
# 修改git代码仓库，只保留给定的子目录（含history）
# 可通过 git log, 或gitk 确认
# 然后可以将其推送到新git仓库
git filter-repo --path risk-protocol
----




== sparse-checkout

[source,shell]
----
# 生成 .git/info/sparse-checkout
git sparse-checkout init
# 打开
git config core.sparseCheckout true
# 关闭
git sparse-checkout disable

# 列出当前
git sparse-checkout list
git sparse-checkout set risk-protocol

----
