=== 安装

http://www.springsource.org/sts[SPRING TOOL SUITE]

=== 强制使用 GTK2

____
==== Issues on Linux (GTK3)

Eclipse 4.5, upon which STS and GGTS are based, is the first Eclipse release where GTK3 is the default for the SWT widget library. There are some issues with this still:

STS New Dashboard doesn’t work under GTK3 because it uses JavaFX which is not currently compatible with GTK3. Instead the old dashboard will open. The Eclipse editor may be slow to respond (Eclipse Bug 434898).

You may also experience other UI rendering glitches. If you exprience any of these problems you can avoid ++>++ them by forcing SWT to switch back to using GTK2. Just set the environment variable "`SWT++_++GTK3=0`" before launching STS or GGTS.
____

==== STS.desktop

....
cat Desktop/STS.desktop
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[en_US]=gnome-panel-launcher
Name[en_US]=STS 3.7
Exec=env SWT_GTK3=0 /usr/local/sts/sts-3.7.2.RELEASE/STS
Icon=/usr/local/sts/sts-3.7.2.RELEASE/icon.xpm
....

##常用插件 ++*++ https://github.com/guari/eclipse-ui-theme[MoonRise UI Theme] ++*++ ??? https://github.com/rogerdudler/eclipse-ui-themes[eclipse-ui-themes] ++*++ http://eclipsecolorthemes.org/[Eclipse Color Themes] ++*++ http://andrei.gmxhome.de/anyedit/[AnyEdit] update site：http://andrei.gmxhome.de/eclipse -++>++ Eclipse 3.5 - 4.2 plugins -++>++ AnyEditTools 配置：STS : Preferences -++>++ General/Editors/AnyEdit Tools ++*++ http://propedit.sourceforge.jp/index_en.html[Properties Editor] update site： http://propedit.sourceforge.jp/eclipse/updates/ ++*++ http://www.eclipse.org/subversive/installation-instructions.php[SVN] 请参照 `Option 2 - Use a Subversive Update Site` ++*++ http://docs.codehaus.org/display/SONAR/Installing+SonarQube+in+Eclipse[Sonar] 最新版Update site: http://dist.sonar-ide.codehaus.org/eclipse/ 历史版本更新站点目录: http://dist.sonar-ide.codehaus.org/eclipse-archives/ 注意：需要根据使用的SonarQuebe服务器的版本而选定Eclipse插件的版本 ++*++ http://eclipse-cs.sourceforge.net/[CheckStyle] 建议使用Sonar插件替代。 ++*++ http://findbugs.sourceforge.net/manual/eclipse.html[Findbugs] 建议使用Sonar插件替代。 update site： http://findbugs.cs.umd.edu/eclipse ++*++ http://pmd.sourceforge.net/[PMD] 建议使用Sonar插件替代。 ++*++ http://ermaster.sourceforge.net/[ERMaster] ++*++ http://amateras.sourceforge.jp/cgi-bin/fswiki_en/wiki.cgi?page=AmaterasUML[AmaterasUML] ++*++ http://amateras.sourceforge.jp/cgi-bin/fswiki_en/wiki.cgi?page=AmaterasERD[AmeterasERD] 需要先安装 AmaterasUML ++*++ https://marketplace.eclipse.org/content/github-flavored-markdown-viewer-plugin-eclipse[GitHub Flavored Markdown viewer plugin for Eclipse]

##其他插件 ++*++ Drools and JBPM :: 可用于研究 jBPM 5更新站点：http://download.jboss.org/drools/release/5.5.0.Final/org.drools.updatesite/ 参考：http://www.jboss.org/drools/downloads

=== 常用快捷键

* Ctrl{plus}Shift{plus}D : Clean Up (需要自定义：STS-Windows-Preferences-General-Keys：Clean Up)
* Ctrl{plus}Shift{plus}F : Format (建议使用Ctrl{plus}Shift{plus}D替代)
* Alt{plus}Shift{plus}J : 追加Javadoc（自动使用Java/Code Style/Code Templates）
* Alt{plus}/ : Word Completion (常常取消该快捷键的绑定)
* Ctrl{plus}Space : Content Assist (常常修改快捷键为Alt{plus}/)

== 常用Preferences设置

....
General->Editors->Text Editors
    : 选中 Insert spaces for tabs
    : 选中 Show print margin, 120
    : 选中 Show line numbers
    : 选中 Show whitespace characters
Web->CSS Files->Editor
    : Line width 修改为 120
    : 选中 Indent using spaces, 设置 Indentation size 为 4
Web->HTML Files->Editor
    : Line width 修改为 120
    : 选中 Indent using spaces, 设置 Indentation size 为 4
XML->XML Files->Editor
    : Line width 修改为 120
    : 选中 Indent using spaces, 设置 Indentation size 为 4

# 可以方便自动提示/完成 "import static"
Java->Editor->Content Assist->Favorites
    : New type
        org.junit.Assert
        com.datastax.driver.core.querybuilder.QueryBuilder
....

=== 加速

* 修改Eclipse.ini/STS.ini中的JVM参数，并http://wiki.eclipse.org/Eclipse.ini#-vm_value:_Linux_Example[指定JVM]：
+
[source,ini]
----
-vm /usr/lib/jvm/java-7-openjdk-amd64/bin/java  # 第一行
# ...
-Xms1024m
-Xmx2000m
-XX:PermSize=128m
-XX:MaxPermSize=512m
-Xss2m
-Xmn128m
-Xverify:none
-server
-XX:+UseParallelGC
-XX:ParallelGCThreads=10
----
* 禁用Dashboard ：Window-++>++Preferences-++>++SpringSource-++>++Dashboard：取消勾选 Show Dashboard On Startup
* 禁用Spell Check：Window-++>++Preferences-++>++General-++>++Editors-++>++Text Editors-++>++Spelling ：取消选择Enable spell checking
* 禁用不需要的validation：Windows -++>++ Preferences -++>++ Validation
* 关闭自动更新：Windows -++>++ Preferences -++>++ Install/Update -++>++ Automatic Updates
* 使用Sun的JDK运行Eclipse/STS
* 将JDK整个放入ramdisk中（？？？貌似不易实施？重启后内容丢失。）
** https://wiki.archlinux.org/index.php/Ramdisk[linux]
+
[source,bash]
----
sudo mkdir -p /media/ramdisk
#sudo mount -t ramfs -o size=256M ramfs /media/ramdisk/
sudo mount -t ramfs none /media/ramdisk/
sudo vi /etc/fstab
none  /mnt/ramdisk    ramfs   defaults,gid=1000,uid=1000      0   0
----
** http://www.softperfect.com/products/ramdisk/[Windows]
* 不要打开过多的工程/关闭不相关的工程
* 不要打开过多的文件/Editor
* 适当的时候，可以关闭auto-build
* 关闭不需要的 label declaration（SVN/GIT）

=== 常用快捷键

[cols=",",options="header",]
|===
|key |desp
|Ctrl{plus}Shift{plus}T |Open Type
|Ctrl{plus}Shift{plus}R |Open Resource
|Ctrl{plus}Shift{plus}R |Open Resource
|===

##常见问题 ###Win7下eclipse3.7中文字体过小 原因：由于Eclipse 3.7 用的字体是 Consolas，显示中文的时候默认太小了。 ++*++ 解决方法一：使用http://font.ubuntu.com/[Ubuntu Mono]字体，建议字号设置为小四。 ++*++ 解决方法二：把字体设置为Courier New 打开Elcipse，点击菜单栏上的“Windows”——点击“Preferences”——点击“Genneral”——点击“Appearance”——点击“Colors and Font”——在右侧框展开“Basic”文件夹–双击“Text Font”——在弹出窗选择“Courier New”——点击按钮“确定”——点击按钮“OK”，完成。

....
提醒：这里可能找不到“Courier New”，点击字体选择框左下角的“显示更多字体”链接来打开设置字体的控制面板，找到“Courier New”，右键选择“显示”即可激活该字体）
....

* 解决方法三：使用混合字体代替Consolas字体
[arabic]
. 下载http://files.cnblogs.com/icelyb24/YaHei.Consolas.1.12.rar[Consolas和微软雅黑混合字体]
. 解压之后，把YaHei.Consolas.1.12.ttfw文件复制到C:，完成字体的安装
. 打开Elcipse，点击菜单栏上的“Windows”——点击“Preferences”——点击“Genneral”——点击“Appearance”——点击“Colors and Font”——在右侧框展开“Basic”文件夹–双击“Text Font”——在弹出窗选择“YaHei.Consolas”——点击按钮“确定”——点击按钮“OK”，完成。 一个不足：键盘上Esc键下面的那个字符和单引号只有宽度上的区别，而没有字形上的区别。

=== Java Clean Up

Preferences - Java - Code Style - Clean Up : 取消选中 "`Show profile selection dialog for the '`Source ++>++ Clean Up`' action`"。 在 Eclipse ++[++build-in++]++ 的基础上进行以下修改：

[arabic]
. Code Organizing : General settings : 选中 Format source code
. Code Organizing : General settings : 选中 Remove trailing whitespace
. Code Organizing : Imports : 选中 Organize imports
. Code Style : Control statements : 选中 Use blocks in if/while/for/do statements
. Code Style : Variable declarations : 选中 Use modifier '`final`' where possible
. Code Style : Variable declarations : 选中 Parameter
. Missing Code : Annotations : Potential programming problems : 选中 Add serial version ID

=== Java Formater

在 Eclipse ++[++build-in++]++ 的基础上做以下修改：

[arabic]
. Identation : General settings : Tab policy 选为 Spaces only
. Line Wrapping : Maximum line width : 120
. Line Wrapping : 选中 Never join already wrapped lines
. Comments : 取消选中 “Enable line comment formatting”
. Comments : 选中 Never join lines
. Comments : Line width : Maximum line width for comments : 120
. Off/On Tags : 选中 Enable Off/On tags

== 字体

YaHei Consolas Hybrid ： 基本能满足等宽编程要求，但是tab键上面的那个字符和单引号很相似，且不等宽。

http://wiki.ubuntu.org.cn/%E5%AD%97%E4%BD%93[文泉驿-微米黑]有点不好看。

最终，还是选择 Microsoft YaHei Mono.ttf

== GGTS

http://grails.org/products/ggts[Groovy/Grails Tool Suite]

=== 安装插件

* spring tool suit
* m2e相关插件
* Spring IDE 相关插件
