
:experimental:

## 15

[source,plain]
----
>> License server
http://idea.lanyus.com
或者
http://www.iteblog.com/idea/key.php
----

## 安装

[source,shell]
----
sudo mkdir /usr/local/idea
sudo tar zxvf ~/Downloads/ideaIU-14.0.3.tar.gz -C /usr/local/idea

vi ~/Desktop/idea14.desktop
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[en_US]=gnome-panel-launcher
Name[en_US]=idea-IU-14.0.3
Exec=/usr/local/idea/idea-IU-139.1117.1/bin/idea.sh
Icon=/usr/local/idea/idea-IU-139.1117.1/bin/idea.png

cd /usr/local/idea/idea-IU-139.1117.1/bin/
sudo cp idea64.vmoptions idea64.vmoptions.bak
sudo vi idea64.vmoptions           // 修改JVM参数
sudo vi idea.sh                    // 在最开始加入  `. /etc/profile.d/xxx.sh`

# 注意： Mac OS X 下，会单独生成文件的保存路径，比如：/Users/zll/Library/Preferences/IntelliJIdea2016.2/idea.vmoptions

----

## 苹果下快捷键

<!-- ↑ ↓ ← → ↖ ↗ ↙ ↘ ↔ ↕  ⬆️⬇️➡️⬅️ -->




|===
|key | description

|kbd:[Cmd+←]|光标移动到行首
|kbd:[Cmd+→]|光标移动到行尾
|kbd:[Cmd+Shift+↑]|选中区域向上移动
|kbd:[Cmd+Shift+↓]|选中区域向下移动
|kbd:[Cmd+/]|注释代码
|kbd:[Cmd+[]|导航：向后
|kbd:[Cmd+\]]|导航：向前
|kbd:[Cmd+Shift+[]|导航：前一个 Tab
|kbd:[Cmd+Shift+\]]|导航：后一个 Tab
|kbd:[Cmd+Backspace]|删除当前行
|kbd:[Cmd+D]|复制当前行
|kbd:[Cmd+Shift+Backspace]|导航：回到最后一次修改处
|kbd:[Cmd+Fn+←]|回到编辑器第一行
|kbd:[Cmd+Fn+→]|回到编辑器最后一行
|kbd:[Cmd+P]|显示参数
|kbd:[Cmd+Shift+E]|显示最近修改的文件
|kbd:[Cmd+Shift+V]|显示最近5次粘贴的内容
|kbd:[Cmd+Option+L]|格式化代码
|kbd:[Cmd+Option+L]|格式化代码
|kbd:[Ctrl+Option+O]|格式化 import
|kbd:[Ctrl+H]|显示选中class的子类
|kbd:[Cmd+-]|折叠
|kbd:[Cmd++]|展开
|kbd:[Shift+Cmd+-]|全部折叠
|kbd:[Shift+Cmd++]|全部展开
|===


# ubuntu 下中文字体

[source,shell]
----
# 安装文泉驿中文字体
sudo apt-get install ttf-wqy-microhei

vi $IDEA_HOME/bin/idea64.vmoptions
-Dawt.useSystemAAFontSettings=lcd
-Dsun.java2d.xrender=true
-Dswing.aatext=true
-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel

#

Settings -> Appearance -> Override default fonts by ... : WenQuanYi Micro Hei Mono 13px
Settings -> Editor
    -> Use anti-aliased font
    -> Colors & Fonts -> Font.  : WenQuanYi Micro Hei Mono 14px

or  YaHei Consolas Hybrid 15px
----
link:http://files.cnblogs.com/icelyb24/YaHei.Consolas.1.12.rar[YaHei.Consolas.1.12.rar]





## 常用设置

从菜单栏打开 File -> Settings :

[source,plain]
----
Appearance && Behavior
    Appearance :
        1. Theme 下拉选择为 "Darcula"
    Keymap :
        1. Keymaps 下拉选择为 "Eclipse"
Editor :
    General :
        Appearance :
            1. 选中 "Show line numbers"
            1. 选中 "Show whitespaces"
    Live Templates :
        other:
            - add `@au`. value `@author dangqian.zll`
Keymap : 复制一份 Eclipse 版的快捷键配置，搜索 close 并
    移除 Window/Active Tool Window/Close Active Tab 的 `Ctrl+W` 的快捷键
    为 Window/Editor Tabs/Close 追加 `Ctrl+W` 的快捷键
    查找F2使用的快捷键，并全部移除，为 Main Menu/Refactor/Rename 增加 F2 快捷键
----

Editor/File and Code Templates :


[source,plain]
----
#if (${PACKAGE_NAME} && ${PACKAGE_NAME} != "")package ${PACKAGE_NAME};#end
#parse("File Header.java")

/**
 * @author 当千
 * @date ${YEAR}-${MONTH}-${DAY}
 */
public class ${NAME} {
}
----


## 插件

* link:http://plugins.jetbrains.com/plugin/7238?pr=idea[sonarqube]
* link:http://plugins.jetbrains.com/plugin/6971?pr=idea[angularjs]
## 通过IP地址访问 build-in server

在nginx/tengin 中加入如下配置文件

[source,plain]
----
server {
    listen 192.168.0.60:63342;
    server_name 192.168.0.60;
    server_tokens off;
    root /notExisted;
    location / {
        proxy_pass              http://localhost:63342;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    }
}
----
### 7788

. 工程中选择输出目录（比如 target，build，dist 等），右键选择 `Mark Directory As` -> `Excluded`
   或者到 `Preferences | Project | Directories` 中排除指定的目录。


### jetbrains license server

use docker [woailuoli993/jblse](https://hub.docker.com/r/woailuoli993/jblse/).

[source,shell]
----
docker create                           \
    --name qh-idea                      \
    --restart unless-stopped            \
    -p 20701:20701                      \
    woailuoli993/jblse

docker start qh-idea

# 认证服务器： http://127.0.0.1:20701
----



### format code

link:https://www.jetbrains.com/help/idea/command-line-formatter.html[Format files from the command line]


"/Users/zll/Applications/IntelliJ IDEA Community Edition.app/Contents/bin/format.sh" -s ~/Default.xml /Users/zll/data0/work/git-repo/ali/chengdun_security_commercialization/deploy_daily/.tmp/a.java

"/Users/zll/Applications/IntelliJ IDEA Ultimate.app/Contents/bin/format.sh" -s ~/Default.xml /Users/zll/data0/work/git-repo/ali/chengdun_security_commercialization/deploy_daily/.tmp/a.java


[source,plain]
----
ormatting /Users/zll/data0/work/git-repo/ali/chengdun_security_commercialization/deploy_daily/.tmp/a.java...2023-10-13 17:04:01,185 [   3134] SEVERE - #c.i.o.progress - This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, or use com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking.
java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, or use com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking.
	at com.intellij.openapi.progress.CoroutinesKt.assertBackgroundThreadOrWriteAction(coroutines.kt:413)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:124)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingMaybeCancellable(coroutines.kt:152)
	at org.editorconfig.configmanagement.extended.EditorConfigCodeStyleSettingsModifier.modifySettings(EditorConfigCodeStyleSettingsModifier.kt:66)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider$AsyncComputation.computeSettings(CodeStyleCachedValueProvider.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider$AsyncComputation.start(CodeStyleCachedValueProvider.kt:135)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider$AsyncComputation.getCurrentResult(CodeStyleCachedValueProvider.kt:212)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider.compute(CodeStyleCachedValueProvider.kt:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:240)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:27)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachedValueProvider.tryGetSettings(CodeStyleCachedValueProvider.kt:47)
	at com.intellij.application.options.codeStyle.cache.CodeStyleCachingServiceImpl.tryGetSettings(CodeStyleCachingServiceImpl.java:53)
	at com.intellij.application.options.CodeStyle.getSettings(CodeStyle.java:115)
	at com.intellij.formatting.ExcludedFileFormattingRestriction.isFormatterAllowed(ExcludedFileFormattingRestriction.java:17)
	at com.intellij.lang.LanguageFormatting.forContext(LanguageFormatting.java:29)
	at com.intellij.lang.LanguageFormatting.forContext(LanguageFormatting.java:23)
	at com.intellij.formatting.commandLine.FileSetCodeStyleProcessorKt.isFormattingSupported(FileSetCodeStyleProcessor.kt:267)
	at com.intellij.formatting.commandLine.FileSetCodeStyleProcessorKt.access$isFormattingSupported(FileSetCodeStyleProcessor.kt:1)
	at com.intellij.formatting.commandLine.FileSetFormatter.processFileInternal(FileSetCodeStyleProcessor.kt:77)
	at com.intellij.formatting.commandLine.FileSetCodeStyleProcessor$processVirtualFile$1.invoke(FileSetCodeStyleProcessor.kt:227)
	at com.intellij.formatting.commandLine.FileSetCodeStyleProcessor$processVirtualFile$1.invoke(FileSetCodeStyleProcessor.kt:220)
	at com.intellij.formatting.commandLine.FileSetCodeStyleProcessor.withStyleSettings(FileSetCodeStyleProcessor.kt:238)
	at com.intellij.formatting.commandLine.FileSetCodeStyleProcessor.processVirtualFile(FileSetCodeStyleProcessor.kt:220)
	at com.intellij.formatting.commandLine.FileSetProcessor.processFiles(FileSetProcessor.kt:91)
	at com.intellij.formatting.commandLine.FormatterStarter.main(FormatterStarter.kt:49)
	at com.intellij.ide.bootstrap.ApplicationLoader$initApplicationImpl$4.invokeSuspend$lambda$0(ApplicationLoader.kt:102)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.ide.bootstrap.ApplicationLoader$initApplicationImpl$4.invokeSuspend(ApplicationLoader.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
----



## file and code Templates

includes
默认的 "File Header.java"

Template text:
[source,java]
----
/**
 *
 * @author dangqian.zll
 * @date ${DATE}
 */
----



## live template


* 类的javadoc

Abbreviation : "jd"
description : "class javadoc"
Template text:

[source,java]
----
/**
 *
 * @author dangqian.zll
 * @date $date$
 */
----

应用在： Java: declaration

variables :  date=`date()`


* 增加 serialVersionUID

Abbreviation : "sv"
description : "serialVersionUID"
Template text:

[source,java]
----
private static final long serialVersionUID = 1L;
----

应用在： Java: declaration

variables :  无

* 增加 lombok

Abbreviation : "d"
description : "add lombok pojo annotation"
Template text:

[source,java]
----
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
----

应用在： Java: declaration

variables :  无


## Mybatis xml mapper 中 sql 高亮，语法校验

Editor/Language Injections

新增：
* 类型：Xml Tag Injection
* Name： 自定义，比如 "my : MyBatis3 sql|select|insert|update|delete|statement"
* Language : SQL
* XML Tag :
** Local name : sql|select|insert|update|delete|statement, 选中 "Sub-tags"
** Namespace : http://mybatis.org/dtd/mybatis-3-mapper.dtd
* Advanced
** Value pattern : 选中 "Single file"



## spellcheck

### project-level
保存在 `.idea/dictionaries/${USERNAME}.xml` 中，比如: `.idea/dictionaries/default_user.xml`。
示例
[source,xml]
----
<component name="ProjectDictionaryState">
  <dictionary name="default.user">
    <words>
      <w>lazada</w>
      <w>yace</w>
    </words>
  </dictionary>
</component>
----


### 自定义dic文件
* link:https://www.jetbrains.com/help/idea/spellchecking.html#dictionaries[Dictionaries﻿]

将
示例： link:spellcheck.dic[spellcheck.dic]

[source,shell]
----
# 操作系统层面
mkdir -p ~/.idea/
CUR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ln -s "${CUR_DIR}/my.dic" ~/.idea/my.dic
echo "${HOME}/.idea/my.dic"

# idea intellij 层面 设置使用自定义 字典
# Settings : Editor : Natural Languages : Spelling : Custom dictionaries : 新加一个 ~/.idea/my.dic

# idea intellij 层面 重新校验 (快捷键: ⌥Option+⇧Shift+⌘Сmd+I)
# 菜单: Code : Anaylyse Code : Run Inspection by Name... : "Typo"
----


== disable inspections

Editor/Inspections:java

[source,java]
----
Java/Java language level migration aids/Java 5/ Raw use of parameterized class
Java/Javadoc/Javadoc declaration problems :          Severity=> Consideration
Spring/Spring Core/Code:Incrorrect autowiring in Spring bean components
----




== Format

- link:https://www.jetbrains.com/help/idea/command-line-formatter.html[Format files from the command line]
- link:https://github.com/diffplug/spotless/tree/main/plugin-maven#intellij-idea[sptless:IntelliJ IDEA]



