FROM alpine
#podman run --cap-add=NET_ADMIN,NET_RAW --name c1 --rm --network=host -it alpine sh
#apk add iputils

# ping, telnet
RUN apk add --no-cache iputils busybox-extras


# podman build -t my-alpine -f Dockerfile
