
* github:

** apache
*** link:https://github.com/apache/rocketmq[rocketmq]
*** link:https://github.com/apache/rocketmq-docker[rocketmq-docker]
*** link:https://github.com/apache/rocketmq-clients[rocketmq-clients]
*** link:https://github.com/apache/rocketmq-dashboard[rocketmq-dashboard]
** alibaba
*** link:https://github.com/alibaba/spring-cloud-alibaba[spring-cloud-alibaba]
*** link:https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-bus-rocketmq/[spring-cloud-starter-bus-rocketmq]
*** link:https://github.com/alibaba/spring-cloud-alibaba/tree/2.2.x/spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq[spring-cloud-starter-stream-rocketmq]


* doc
** link:https://rocketmq.apache.org/[rocketmq]

== docker

[source,shell]
----

docker run -it --rm \
  o-docker.alibaba-inc.com/docker.io/rocketmq:5.3.1 \
  bash -l

docker run -d \
-p 10911:10911 -p 10909:10909 \
-v `pwd`/data/broker/logs:/root/logs \
-v `pwd`/data/broker/store:/root/store \
-v `pwd`/data/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf \
--name rmqbroker \
--link rmqnamesrv:namesrv \
-e "NAMESRV_ADDR=namesrv:9876" \
o-docker.alibaba-inc.com/docker.io/rocketmq:5.3.1 \
sh mqbroker \
-c /home/rocketmq/rocketmq-4.5.0/conf/broker.conf

----


== SDK
=== 旧：remoting 协议

典型接口：

* org.apache.rocketmq.common.message.Message
* org.apache.rocketmq.client.consumer.DefaultMQPushConsumer
* org.apache.rocketmq.client.producer.MQProducer
* org.apache.rocketmq.client.producer.DefaultMQProducer
* org.apache.rocketmq.client.producer.SendResult

[source,xml]
----
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client</artifactId>
    <version>5.2.0</version>
</dependency>
----

link:https://rocketmq.apache.org/docs/4.x/bestPractice/06log/[Logging Confituration]

[source,java]
----
public class Demo{
    void send01(){
        MQProducer producer = new DefaultMQProducer("producer_group_1");
        producer.start();
        Message msg = new Message(
            "xxxTopic",
            new String[]{"TagA", "TagB"},
            "msgKey1",
            "hello world".getBytes(StandardCharsets.UTF_8)
        );
        SendResult sendResult = producer.send(msg);
        producer.shutdown();
    }
    void receive01(){
        DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("consumer_group_1");
        consumer.setConsumeFromWhere(ConsumeFromWhere.CONSUME_FROM_FIRST_OFFSET);
        consumer.subscribe("TopicTest", "TagA || TagC || TagD");
        consumer.registerMessageListener((List<MessageExt> msgs, ConsumeOrderlyContext context)-> {
            context.setAutoCommit(false);
            // ...
            return ConsumeOrderlyStatus.SUCCESS;
        });
        consumer.start();
    }
}
----


=== 新：gRpc 协议

典型接口：

* rocketmq-client-java.jar!apache/rocketmq/v2/service.proto
* org.apache.rocketmq.client.apis.message.Message
* org.apache.rocketmq.client.apis.ClientServiceProvider
* org.apache.rocketmq.client.apis.producer.Producer
* org.apache.rocketmq.client.java.impl.producer.ProducerImpl
* org.apache.rocketmq.client.apis.ClientServiceProvider
* org.apache.rocketmq.client.apis.consumer.PushConsumer
* org.apache.rocketmq.client.apis.producer.SendReceipt
* org.apache.rocketmq.client.java.hook.MessageInterceptor


[source,xml]
----
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>rocketmq-client-java</artifactId>
    <version>5.0.6</version>
</dependency>
----

[source,java]
----
public class Demo {
    void send01() {
        ClientConfiguration clientConfiguration = ClientConfiguration.newBuilder()
                .setEndpoints("127.0.0.1:8082")
                .setCredentialProvider(new StaticSessionCredentialsProvider("ak1", "sk1"))
                .enableSsl(false)
                .build();
        Producer producer = provider.newProducerBuilder()
                .setClientConfiguration(clientConfiguration)
                // 可选但推荐，预计要发送的topic列表，如果提前设置，则可以prefetch消息的路由信息
                .setTopics("topic1","topic2")
                .build();
        final Message message = provider.newMessageBuilder()
                .setTopic("topic1")
                .setTag("TagA")
                .setKeys("msgKey1")
                .setBody("hello world".getBytes(StandardCharsets.UTF_8))
                .build();
        final SendReceipt sendReceipt = producer.send(message);
        producer.close();
    }
    void receive01() {
        ClientConfiguration clientConfiguration = ClientConfiguration.newBuilder()
            .setEndpoints("127.0.0.1:8082")
            .setCredentialProvider(new StaticSessionCredentialsProvider("ak1", "sk1"))
            .enableSsl(false)
            .build();
        ClientServiceProvider provider = ClientServiceProvider.loadService();
        SimpleConsumer consumer = provider.newSimpleConsumerBuilder()
            .setClientConfiguration(clientConfiguration)
            .setConsumerGroup(consumerGroup)
            .setAwaitDuration(Duration.ofSeconds(30))
            .setSubscriptionExpressions(Collections.singletonMap(
                topic, new FilterExpression("TagA", FilterExpressionType.TAG))
            )
            .build();

        final List<MessageView> messages = consumer.receive(16, Duration.ofSeconds(15));
        for (MessageView message : messages) {
            final MessageId messageId = message.getMessageId();
            // ...
            consumer.ack(message);
        }
    }
}
----


== server

=== 5.x

==== 示例启动

[source,shell]
----
export ROCKETMQ_HOME=$HOME/Downloads/rocketmq-all-5.1.0-bin-release
export NAMESRV_ADDR=localhost:9876
cd $ROCKETMQ_HOME

# 启动NameServer
./bin/mqnamesrv

# 启动Broker+Proxy
./bin/mqbroker -n localhost:9876 --enable-proxy
----

==== nameServer
java 核心类：

* link:https://github.com/apache/rocketmq/blob/bd7db7ec62164882ce6db101bacd038308648e02/namesrv/src/main/java/org/apache/rocketmq/namesrv/NamesrvStartup.java#L43[org.apache.rocketmq.namesrv.NamesrvStartup] # main函数主类
* link:https://github.com/apache/rocketmq/blob/bd7db7ec62164882ce6db101bacd038308648e02/common/src/main/java/org/apache/rocketmq/common/namesrv/NamesrvConfig.java#L19[org.apache.rocketmq.common.namesrv.NamesrvConfig] # 配置项对应的java类
* https://github.com/apache/rocketmq/blob/70480a1fa9aac397fa8c5dbcb352284ad118a891/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyServerConfig.java#L19[org.apache.rocketmq.remoting.netty.NettyServerConfig]
** listenPort : 10911

* link:https://github.com/apache/rocketmq/blob/70480a1fa9aac397fa8c5dbcb352284ad118a891/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyClientConfig.java#L23[org.apache.rocketmq.remoting.netty.NettyClientConfig]

配置文件由命令 mqnamesrv的参数 -c指定，格式是  properties 文件。

[source,properties]
----
rocketmqHome=                 # RocketMQ主目录，默认用户主目录
namesrvAddr=                  # NameServer地址
kvConfigpath=                 # kv配置文件路径，包含顺序消息主题的配置信息
configStorePath=              # NameServer配置文件路径，建议使用-c指定NameServer配置文件路径
clusterTest=                  # 是否支持集群测试，默认: false
orderMessageEnable=           # 是否支持顺序消息，默认: false
----

==== broker
java 核心类：

* link:https://github.com/apache/rocketmq/blob/bd7db7ec62164882ce6db101bacd038308648e02/broker/src/main/java/org/apache/rocketmq/broker/BrokerStartup.java#L44[org.apache.rocketmq.broker.BrokerStartup]  # main函数主类
* https://github.com/apache/rocketmq/blob/70480a1fa9aac397fa8c5dbcb352284ad118a891/common/src/main/java/org/apache/rocketmq/common/BrokerConfig.java#L26[org.apache.rocketmq.common.BrokerConfig]   # 配置项对应的java类
** #aclEnable                              # 是否开启ACL权限控制
* link:https://github.com/apache/rocketmq/blob/70480a1fa9aac397fa8c5dbcb352284ad118a891/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyServerConfig.java#L19[org.apache.rocketmq.remoting.netty.NettyServerConfig]
** listenPort : 10911
* link:https://github.com/apache/rocketmq/blob/70480a1fa9aac397fa8c5dbcb352284ad118a891/remoting/src/main/java/org/apache/rocketmq/remoting/netty/NettyClientConfig.java#L23[org.apache.rocketmq.remoting.netty.NettyClientConfig]
* link:https://github.com/apache/rocketmq/blob/70480a1fa9aac397fa8c5dbcb352284ad118a891/store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java#L195[org.apache.rocketmq.store.config.MessageStoreConfig]
** haListenPort: 10912

* org.apache.rocketmq.acl.plain.PlainAccessData  #
* org.apache.rocketmq.common.PlainAccessConfig

配置文件由命令 mqbroker的参数 -c指定，格式是  properties 文件。
默认是： conf/broker.conf



==== proxy
java 核心类：

* org.apache.rocketmq.proxy.ProxyStartup # main函数主类
* org.apache.rocketmq.proxy.config.ProxyConfig # 配置文件对应的 java 类

配置文件由命令 mqproxy 的参数 -pc(--proxyConfigPath)指定，格式是  json 文件。
jvm 系统属性: com.rocketmq.proxy.configPath
默认配置文件: rmq-proxy.json
[source,json]
----
{
  "rocketMQClusterName"  : "DefaultCluster",
  "grpcServerPort"       : 8081
}
----


==== 其他
* $HOME/controller/controller.properties  # ControllerConfig#configStorePath
* $HOME/namesrv/kvConfig.json             # NamesrvConfig#kvConfigPath
* $HOME/namesrv/namesrv.properties        # NamesrvConfig#configStorePath




== client

=== java

==== rocketmq-spring
github:

* link:https://github.com/apache/rocketmq-spring[rocketmq-spring]
**  maven: link:https://search.maven.org/search?q=g:org.apache.rocketmq%20a:rocketmq-spring-boot-starter[org.apache.rocketmq:rocketmq-spring-boot-starter]
** link:https://github.com/apache/rocketmq-spring/wiki/Send-Message[wiki]
** link:https://github.com/apache/rocketmq-spring/tree/master/rocketmq-spring-boot-samples[rocketmq-spring-boot-samples]

核心java类：

* org.apache.rocketmq.spring.core.RocketMQTemplate
** #send
** #receive
* org.apache.rocketmq.spring.autoconfigure.RocketMQProperties
* org.apache.rocketmq.spring.core.RocketMQListener#onMessage
* org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration

示例配置

[source,properties]
----
rocketmq.producer.send-message-timeout=3000
rocketmq.producer.compress-message-body-threshold=4096
rocketmq.producer.max-message-size=4194304
rocketmq.producer.retry-times-when-send-async-failed=0
rocketmq.producer.retry-next-server=true
rocketmq.producer.retry-times-when-send-failed=2
----

==== spring-cloud-starter-stream-rocketmq

github

* alibaba/spring-cloud-alibaba ：
** link:https://github.com/alibaba/spring-cloud-alibaba/wiki/RocketMQ-en[Spring Cloud Alibaba RocketMQ Binder]
*** maven GAV: `com.alibaba.cloud:spring-cloud-stream-binder-rocketmq`
*** maven GAV: `com.alibaba.cloud:spring-cloud-starter-stream-rocketmq`

核心java类

* org.springframework.cloud.stream.binder.rabbit.properties.RabbitBinderConfigurationProperties  # prefix = "spring.cloud.stream.rabbit.binder"
* org.springframework.cloud.stream.binder.rabbit.properties.RabbitBindingProperties
* org.springframework.cloud.stream.binder.rabbit.properties.RabbitCommonProperties
* org.springframework.cloud.stream.binder.rabbit.properties.RabbitConsumerProperties
* org.springframework.cloud.stream.binder.rabbit.properties.RabbitExtendedBindingProperties      # prefix = "spring.cloud.stream.rabbit"
* org.springframework.cloud.stream.binder.rabbit.properties.RabbitProducerProperties



=== mqadmin

[source,shell]
----

#podman run -rm apache/rocketmq:4.9.4

export ROCKETMQ_HOME=$HOME/Downloads/rocketmq-all-5.1.0-bin-release
export NAMESRV_ADDR=localhost:9876
export NAMESRV_ADDR=11.167.75.235:9876
cd $ROCKETMQ_HOME

# 参考 org.apache.rocketmq.acl.common.SessionCredentials
cat <<EOF | sudo tee -a ~/key
AccessKey=xxx
SecretKey=yyy
EOF


# 显示完整命令列表
./bin/mqadmin

# ------------------------------ 集群
./bin/mqadmin clusterList



# 检查 topic 是否存在
./bin/mqadmin topicList -c
# 创建/更新 topic
./bin/mqadmin updateTopic -c DefaultCluster -p 6 -t yourNormalTopic
# 删除 topic
./bin/mqadmin deleteTopic -c DefaultCluster -t yourNormalTopic
./bin/mqadmin topicStatus -t mtee3_dispatch

# 根据msgId查询消息
./bin/mqadmin queryMsgByUniqueKey   -t mtee3_dispath -i AC1058F7004D6718465C5B024C7D001F
# 根据消息 Key 查询消息
./bin/mqadmin queryMsgByKey         -t mtee3_dispath -k 172.16.88.247_79_MTEE3_1692346077297_77
# 根据offsetMsgId查询消息
./bin/mqadmin queryMsgById          --msgId AC1058F7004D6718465C5B024C7D001F
----



=== http api

[source,shell]
----
ROCKETMQ_SERVER=http://11.167.75.235:8080
MSG_ID=AC1058F7004D6718465C5B024C7D001F
MQ_TOPIC=mtee3_dispatch
curl "${ROCKETMQ_SERVER}/message/viewMessage.query?msgId=${MSG_ID}&topic=${MQ_TOPIC}" \
  -H 'Accept: application/json, text/plain, */*' \
  --compressed \
  -s \
  --insecure | jq -M -r '.data.messageView.messageBody' > /tmp/a.txt
----


=== 权限控制
* 阿里云：云消息队列 RocketMQ版: 4.x系列: 开发参考：SDK参考：link:https://help.aliyun.com/zh/apsaramq-for-rocketmq/cloud-message-queue-rocketmq-4-x-series/developer-reference/three-modes-used-to-send-normal-messages?spm=a2c4g.11186623.0.0.31a837cekfr3SM[社区版TCP协议SDK（仅供开源用户上云使用）]

* example : link:https://github.com/apache/rocketmq/blob/b18e564addbcff50165a5e1d9d4ab7db789d901b/example/src/main/java/org/apache/rocketmq/example/simple/AclClient.java#L45[AclClient]
* org.apache.rocketmq.remoting.RPCHook
* org.apache.rocketmq.acl.common.AclClientRPCHook

  maven GAV : `org.apache.rocketmq:rocketmq-acl`

* org.apache.rocketmq.client.producer.DefaultMQProducer#DefaultMQProducer(org.apache.rocketmq.remoting.RPCHook)


== 新 gRPC协议 相关hook

=== org.apache.rocketmq.client.java.hook.MessageInterceptor


----
// 配置: consumer side
org.apache.rocketmq.client.java.impl.ClientImpl#<init>
  org.apache.rocketmq.client.java.hook.CompositedMessageInterceptor#<init>

// producer side
org.apache.rocketmq.client.java.impl.producer.ProducerImpl#send
  org.apache.rocketmq.client.java.message.PublishingMessageImpl#<init>
  #send0
    org.apache.rocketmq.client.java.message.GeneralMessageImpl#<init>
    #doBefore
      org.apache.rocketmq.client.java.hook.CompositedMessageInterceptor#doBefore
    org.apache.rocketmq.client.java.impl.ClientManagerImpl#sendMessage  // ⭕️
      org.apache.rocketmq.client.java.rpc.RpcClientImpl#sendMessage
        apache.rocketmq.v2.MessagingServiceGrpc.MessagingServiceFutureStub#sendMessage
                  // ⭕️ 该类是通过 rocketmq-client-java.jar!apache/rocketmq/v2/service.proto 自动生成的
    #doAfter
      org.apache.rocketmq.client.java.hook.CompositedMessageInterceptor#doAfter

----


== 旧 remoting协议相关hook

=== org.apache.rocketmq.remoting.RPCHook

netty 层面 处理 remoteAddr 和 RemotingCommand 的相关扩展点，较少使用。


注册

[source,plain]
----
// provider side
org.apache.rocketmq.client.producer.DefaultMQProducer#<init>  # 构造函数传入 RPCHook
  org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl#<init>

org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl#start
  #getOrCreateMQClientInstance
    org.apache.rocketmq.client.impl.factory.MQClientInstance#<init>
      org.apache.rocketmq.client.impl.MQClientAPIImpl#<init>
        org.apache.rocketmq.remoting.RemotingService#registerRPCHook

----

调用

[source,plain]
----
org.apache.rocketmq.client.impl.MQClientAPIImpl#sendMessage
  #sendMessageSync
    org.apache.rocketmq.remoting.netty.NettyRemotingClient##invokeSync  // ⭕️
      com.alibaba.rocketmq.remoting.netty.NettyRemotingClient#doBeforeRequests
        com.alibaba.rocketmq.remoting.RPCHook#doBeforeRequest
----




=== org.apache.rocketmq.client.hook.SendMessageHook

[source,plain]
----
// 注册 - apache rocketmq

com.taobao.metaq.client.MetaProducer#init
  #registerHooks
  com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl#registerSendMessageHook
  com.taobao.metaq.client.util.HookServiceLoadUtil#loadAllHooks

// 调用 - apache rocketmq
# com.alibaba.security.gong9.mw.pandora.metaq.impl.rocketmq.DefaultIMetaProducer#send
com.taobao.metaq.client.MetaProducer#send
  com.alibaba.rocketmq.client.producer.DefaultMQProducer#send
    com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl#send
      #sendDefaultImpl
        #selectOneMessageQueue
        #sendKernelImpl
        #executeSendMessageHookBefore   // ⭕️
        com.alibaba.rocketmq.client.impl.MQClientAPIImpl#sendMessage
        #executeSendMessageHookAfter    // ⭕️
----


=== org.apache.rocketmq.client.hook.ConsumeMessageHook

[source,plain]
----

// 注册 - apache recketmq : push
org.apache.rocketmq.client.consumer.DefaultMQPushConsumer#<init>
  org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl#registerConsumeMessageHook
        // ⚠️ 这里是硬编码注册，如果想自定义扩展，可以后续自行调用 DefaultMQPushConsumer#registerConsumeMessageHook。

// 调用 - apache recketmq : push
org.apache.rocketmq.client.impl.consumer.PullMessageService#run
org.apache.rocketmq.client.impl.consumer.PullMessageService#pullMessage
org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl#pullMessage
org.apache.rocketmq.client.impl.consumer.PullAPIWrapper#pullKernelImpl
org.apache.rocketmq.client.consumer.PullCallback#onSuccess
  org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService#submitConsumeRequest
    org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest#run
      org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl#executeHookAfter

// 注册 - apache recketmq : pull
org.apache.rocketmq.client.consumer.DefaultLitePullConsumer#start
  #setTraceDispatcher()
    org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl#registerConsumeMessageHook
        // ⚠️ 这里是硬编码注册，如果想自定义扩展，
        // 只能通过反射获取 DefaultLitePullConsumer#defaultLitePullConsumerImpl, 在调用 DefaultLitePullConsumerImpl#registerConsumeMessageHook


// 注册 - alibaba metaq : pull
com.taobao.metaq.client.MetaPullConsumer#<init>
  com.taobao.metaq.client.impl.MetaPullConsumerImpl#<init>
       // ⚠️ 这里是硬编码注册，如果想自定义扩展，
       // 可以后续自行调用 MetaPullConsumer#getMetaPullConsumerImpl().registerConsumeMessageHook()

// 调用 - alibaba metaq : pull
com.taobao.metaq.client.MetaPullConsumer#pullBlockIfNotFound

// 注册 - alibaba metaq : push
com.taobao.metaq.client.MetaPushConsumer#<init>
  com.taobao.metaq.client.impl.MetaPushConsumerImpl#<init>
com.taobao.metaq.client.MetaPushConsumer#start
  com.taobao.metaq.client.impl.MetaPushConsumerImpl#start
    #init
      #registerHooks
        com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl#registerConsumeMessageHook
             // ⚠️ 这里是硬编码注册，如果想自定义扩展，可稍后通过以下方式自定义编程实现。
             // MetaPushConsumer#getMetaPushConsumerImpl().getDefaultMQPushConsumerImpl().registerConsumeMessageHook()


// 鹰眼相关实现：
com.taobao.metaq.trace.core.hook.MetaQSendMessageHookImpl

com.taobao.metaq.trace.core.hook.MetaQConsumeMessageHookImpl

  #consumeMessageBefore
    com.taobao.metaq.trace.core.sub.MetaQConsumeMessageTraceLog#consumeMessageBefore
      #recordSingleMsgBeforeConsume
        com.taobao.eagleeye.EagleEye#setRpcContext
        com.taobao.eagleeye.EagleEye#rpcServerRecv
  #consumeMessageAfter
    com.taobao.metaq.trace.core.sub.MetaQConsumeMessageTraceLog#consumeMessageAfter
      com.taobao.eagleeye.EagleEye#rpcServerSend
      #recordSingleMsgBeforeConsume
        com.taobao.eagleeye.EagleEye#setRpcContext
        com.taobao.eagleeye.EagleEye#rpcServerRecv
----



