

## 产品列表


// 示例1：最简单demo
:table-caption: 产品列表
[#my-tbl1,cols="1,1,1"]
.table1 title
|===
|产品线名称|产品名称｜产品code｜

|弹性计算|云服务器ECS|ecs|
|弹性计算|专有宿主机|ddh|
|弹性计算|弹性伸缩|ess|
|弹性计算|资源编排|ros|
|弹性计算|运维编排服务|oos|
|弹性计算|弹性裸金属服务器|xdragon|
|弹性计算|GPU云服务器|ecsgpu|
|云原生|日志服务|sls|
|存储|块存储EBS|disk|
|存储|对象存储|oss|
|存储|表格存储|ots|
|存储|文件存储NAS|nas|
|云网络|专有网络VPC(ipv4)|vpc|
|云网络|高速通道|expressconnect|
|云网络|弹性公网IP|eip|
|云网络|共享带宽|cbwp|
|云网络|传统型负载均衡CLB|slb|
|安全|密钥管理服务(仅对内)|kms|
|安全|DDoS基础防护(仅对内)|ddosbasic|
|开放平台|资源管理|resourcemanage|
|开放平台|操作审计|actiontrail|
|网络研发|云解析 PrivateZone|pvtz|
|数据库|云数据库 Redis 版(本地盘)|kvstore|
|数据库|云数据库 RDS MySQL 版(本地盘)|mysql|
|数据库|云数据库 MongoDB 版(本地盘)|mongodb|
|云网络|智能接入网关|smartag|
|安全|DDoS防护|ddos|
|安全|Web应用防火墙|waf|
|安全|内容安全|lvwang|
|安全|全局|cas|
|安全|应用身份服务(IDaaS)|idaas|低(待确认)|
|安全|云安全中心(态势感知)|sas|
|云原生|云监控|cms|
|开放平台|访问控制|ram|
|开放平台|配置审计|config|
|网络研发|云解析DNS|dns|
|CDN及边缘云产研业务部|CDN|cdn|
|CDN及边缘云产研业务部|安全加速 SCDN|scdn|
|CDN及边缘云产研业务部|边缘节点服务 ENS|ens|
|CDN及边缘云产研业务部|全站加速|dcdn|

|云通信|短信服务|dysms|
|云通信|语音服务|dyvms|
|视频云|视频直播|live|

|弹性计算|弹性容器实例|eci|
|弹性计算|服务器迁移中心|smc|
|存储|混合云备份服务(标准版)|hbr|
|云网络|应用型负载均衡ALB(七层)|slb|
|云网络|云企业网(企业版TR)|cbn|
|云网络|私网连接|privatelink|
|云网络|VPN网关(不包含bgp功能)|vpn|
|云网络|NAT网关|nat|
|云网络|全球加速|ga|
|安全|运维安全中心(堡垒机)|bastionhost|

|安全|数据库审计|dbaudit|
|安全|DDoS防护(DDoS原生防护)|ddos|
|安全|云防火墙(高级版-互联网边界防火墙)|cfw|
|安全|加密服务|hsm|
|弹性计算|容器服务Kubernetes版|csk|
|弹性计算|容器镜像服务(企业版)|acr|
|云原生|消息服务|mns|
|云原生|Prometheus监控服务|prometheus|
|云原生|消息队列Kafka版|alikafka|
|云原生|微服务引擎|mse|
|云原生|应用实时监控服务(应用监控)|arms|
|数据库|云数据库 Redis 版(云盘版)|kvstore|
|数据库|云数据库 RDS MySQL 版(云盘版)|mysql|
|数据库|云数据库 MongoDB 版(云盘版)|mongodb|
|数据库|云数据库 RDS SQL Server 版(云盘版)|sqlserver|
|数据库|云数据库 RDS PostgreSQL 版(云盘版)|postgresql|
|数据库|云原生多模数据库Lindorm|hitsdb|
|数据库|云数据库HBase版|hbase|
|数据库|数据库自治服务(基础版)|hdm|
|数据库|数据库备份|dbs|
|数据库|数据管理|dms|
|数据传输服务DTS(基础版)|dts|
|数据库|云原生分布式数据库 PolarDB-X|drds|
|数据库|云原生数据仓库AnalyticDB MySQL版|ads|
|数据库|云原生数据仓库 AnalyticDB PostgreSQL版|gpdb|
|云原生|API 网关|apigateway|
|计算平台|PAI|learn|
|计算平台|Dataworks|dide|
|计算平台|MaxCompute|odps|
|计算平台|hologres|hologram|
|计算平台|flink|sc|
|计算平台|ElasticSearch|elasticsearch|
|===






[source,plain]
----
jq -r '.data[]|"|"+.productCode +"|"+.ramCodes+"|"+.productName +"|"' .tmp/a.json
|ecs|ecs|云服务器 ECS|
|ecsgpu|ecs|GPU云服务器|
|xdragon|ecs|弹性裸金属服务器|
|scc|ecs|超级计算集群|
|ddh|ecs|专有宿主机|
|alinux|ecs|Alibaba Cloud Linux 2|
|faas|ecs|FPGA 云服务器|
|disk|ecs|块存储|
|ebs|ebs|块存储EBS|
|ess|ess|弹性伸缩|
|acs|cs|容器服务|
|csk|cs|容器服务Kubernetes版|
|batchcompute|batchcompute|批量计算|
|ros|ros|资源编排|
|fc|fc|函数计算|
|swas|swas|轻量应用服务器|
|ehpc|ehpc|弹性高性能计算|
|acr|cr|容器镜像服务|
|gws|gws|云桌面|
|gwsecd|ecd|无影云桌面|
|eci|eci|弹性容器实例|
|fnf|fnf|Serverless 工作流|
|webx|webplus|Web应用托管服务|
|eais|eais|弹性加速计算实例|
|CloudBox|cloudbox|云盒|
|cloudphone|cloudphone|弹性云手机|
|computenest|computenest,computenestsupplier|计算巢服务|
|vmwaresrv|acvs|VMware服务|
|smc|smc|服务器迁移中心|
|rds|rds|关系型数据库|
|mysql|rds|云数据库 MySQL 版|
|sqlserver|rds|云数据库 SQL Server 版|
|postgresql|rds|云数据库 PostgreSQL 版|
|ppas|rds|云数据库 PPAS 版|
|cddc|rds|云数据库专属集群|
|kvstore|kvstore|云数据库 Redis 版|
|ocs|kvstore|云数据库 Memcache 版|
|mongodb|dds|云数据库 MongoDB 版|
|gpdb|gpdb|云原生数据仓库 AnalyticDB PostgreSQL版|
|petadata|petadata|HybridDB for MySQL（已下线）|
|dts|dts|数据传输|
|dms|dms|数据管理|
|ots|ots|表格存储|
|ads|adb|云原生数据仓库AnalyticDB MySQL版|
|drds|drds,polardbx|云原生分布式数据库 PolarDB-X|
|hbase|hbase|云数据库HBase版|
|adam|adam|数据库和应用迁移|
|polardb|polardb|云原生关系型数据库 PolarDB|
|cbs|dbs|数据库备份|
|hdm|hdm|数据库自治服务|
|openanalytics|openanalytics|云原生数据湖分析|
|gds|gdb|图数据库|
|dbes|dbes|数据库专家服务|
|oceanbase|oceanbase|云数据库OceanBase|
|cds|cassandra|云数据库Cassandra版|
|ledgerdb|ledgerdb|可信账本数据库|
|clickhouse|clickhouse|云数据库 ClickHouse 版|
|dg|dg|数据库网关DG（公测中）|
|oss|oss|对象存储|
|nas|nas|文件存储NAS|
|hcs_hgw|hgw|混合云存储|
|hcs_sgw|hcs-sgw|云存储网关|
|cloudphoto|cloudphoto|智能云相册|
|hbr|hbr|混合云备份服务|
|hdr|hdr|混合云容灾服务|
|imm|imm|智能媒体管理|
|alidfs|dfs|文件存储HDFS|
|dbfs|dbfs|数据库文件存储|
|pds|pds|相册与网盘服务|
|dysms|dysms|短信服务|
|dycdps|dycdp|流量服务|
|dyvms|dyvms|语音服务|
|dypls|dypls|号码隐私保护|
|dypns|dypns|号码认证服务|
|snsu|snsu|云通信网络加速|
|aiccs|aiccs|智能联络中心|
|aliyuncvc|aliyuncvc|钉钉会议|
|imp|imp|互动直播|
|dytns|dytns|号码百科|
|slb|slb|负载均衡|
|alb|alb|应用型负载均衡|
|vpc|vpc|专有网络VPC|
|expressconnect|vpc,expressconnectrouter|高速通道|
|nat|vpc|NAT网关|
|vpn|vpc|VPN网关|
|cbwp|vpc|共享带宽|
|ipv6trans|vpc|IPv6转换服务|
|uis|iotcc|云连接器|
|eip|vpc|弹性公网IP|
|eipanycast|eipanycast|任播弹性公网IP|
|ga|ga|全球加速|
|pvtz|pvtz|云解析 PrivateZone|
|cbn|cen|云企业网|
|smartag|smartag|智能接入网关|
|privatelink|privatelink|私网连接|
|arms|arms|应用实时监控服务|
|cms|cms|云监控|
|advisor|advisor|智能顾问|
|iac|iacservice|IaC服务|
|cloudshell|cloudshell|云命令行|
|config|config|配置审计|
|composer|composer|逻辑编排|
|oos|oos|运维编排|
|cmn|cmn|云网管|
|governance|governance|云治理中心|
|srvcatalog|servicecatalog|服务目录|
|edas|edas|企业级分布式应用服务|
|ons|mq,rocketmq|消息队列 RocketMQ 版|
|onsmqtt|mq|微消息队列 MQTT 版|
|onsproxy|amqp|消息队列 RabbitMQ 版|
|csb|csb|云服务总线 CSB|
|pts|pts|性能测试|
|mns|mns|消息服务|
|txc|txc|全局事务服务|
|acms|acms|应用配置管理|
|alikafka|alikafka|消息队列Kafka版|
|ahas|ahas|应用高可用服务|
|sae|sae|Serverless 应用引擎|
|servicemesh|servicemesh|服务网格|
|eventbridge|eventbridge|事件总线|
|cdn|cdn|CDN|
|vod|vod|视频点播|
|mts|mts|媒体处理|
|live|live|视频直播|
|liveproducer|live-interaction|直播互动|
|pcdn|pcdn|PCDN|
|scdn|scdn|安全加速 SCDN|
|rtc|rtc|音视频通信|
|ens|ens|边缘节点服务 ENS|
|dcdn|dcdn|全站加速|
|vs|vs|视图计算|
|ivision|ivision|智能视觉|
|ice|ice|智能媒体生产|
|hcs_mgw|mgw|闪电立方|
|apigateway|apigateway|API 网关|
|directmail|dm|邮件推送|
|alimail|alimail|阿里邮箱|
|codestore|rpa|机器人流程自动化|
|cd|itaas-cd|云投屏|
|entconsole|resourcemanager|资源管理|
|ressharing|resourcesharing|资源共享|
|resourcetag|tag|标签|
|yida|yida|宜搭|
|apds|apds|云迁移中心|
|mse|mse|微服务引擎|
|msegtw|microgw|微服务网关|
|cloudesl|cloudesl|云价签|
|teambition|teambition|Teambition|
|sofa|sofa|金融分布式架构|
|assettech|assettech|云行情|
|bizworks|bizworks|BizWorks|
|alicloudproc|alicloudproc|阿里云企业采购数字化产品|
|cloudgame|cloudgame|云游戏平台|
|adp|adp|云原生应用交付平台|
|cps|mpush,mhub|移动推送|
|man|man|移动数据分析|
|qaplus|quicktracking|全域用户行为洞察分析平台|
|hotfix|hotfix|移动热修复|
|feedback|feedback,mhub|移动用户反馈|
|mqc|mqc|移动测试|
|emas|emasdevops,mhub|移动研发平台|
|miniappdev|mpca,mpserverless|小程序云&小程序 Severless|
|domain|domain|域名|
|dns|alidns|云解析 DNS|
|geoip|geoip|IP地理位置库|
|httpdns|httpdns|HTTPDNS|
|trademark|trademark|商标服务|
|swcopyright|copyright|版权与专利服务|
|companyreg|companyreg|工商财税|
|premiumpics|premiumpics|图片与设计|
|sca|sca|智能对话分析|
|beebot|chatbot|智能对话机器人|
|ccc|ccc|云呼叫中心|
|retailbot|retailbot|新零售智能助理（SaaS）|
|outboundbot|outboundbot|智能外呼机器人|
|idrsservice|idrsservice|智能双录质检|
|baas|baas|区块链服务|
|baasdis|baasdis|分布式数字身份|
|baascccs|baascccs|可信计算服务|
|aidesign|luban|智能设计|
|gemp|gemp|运维事件中心|
|Genomics|easygene|基因分析平台|
|learn|pai,paiflow,paidesigner,paidlc,paidsw,paiimage,paicodesource,paidataset,paitrainingservice,paimodel,eas,paiworkspace,paitraining,pai_*,pai*|机器学习|
|nls|nls|智能语音交互|
|ocr|ocr|印刷文字识别|
|face|viapi-facebody|人脸识别|
|image|viapi-imagerecog|图像识别|
|nlp|nlp,alinlp,nlp-automl|自然语言处理|
|nlpvision|nlp-vision|智能短信解析|
|imagesearch|imagesearch|图像搜索|
|alimt|alimt|机器翻译|
|cityvisual|cityvisual|城市视觉智能引擎|
|ettraffic|ettraffic|交通云控平台|
|vcs|vcs|视觉计算服务|
|retailir|retailir|货架商品识别与管理|
|multimediaai|multimediaai|多媒体AI|
|ivst|ivst|智能视频字幕|
|discovery|svgp|短视频生产平台|
|tdsr|tdsr|三维空间重建|
|rsimganalys|rsimganalys|数知地球 AI Earth|
|ivpd|ivpd|智能视觉生产|
|addrp|address-purification|地址标准化|
|aliyunape|aliyunape|数智气象引擎|
|viapi|viapi-imageenhan,viapi-imagerecog,viapi-imageseg,viapi-ocr,viapi-facebody,viapi-objectdet,viapi-imageaudit,viapi-goodstech,viapi-imgsearch,viapi-videorecog,viapi-videoenhan,viapi-videoseg,viapi-imageprocess,viapi-threedvision|视觉智能开放平台|
|holowatcher|holowatcher|全息空间|
|opt|opt|优化求解器|
|iot|iot|物联网平台|
|linkanalytics|iot|物联网数据分析服务|
|iotedge|iot|物联网边缘计算|
|hitsdb|lindorm,hitsdb|云原生多模数据库Lindorm|
|dyiot|dyiot,linkcard|物联网无线连接服务|
|iovcc|iovcc|智联车管理云平台|
|linkwan|linkwan|物联网络管理平台|
|linkvisual|linkvisual|物联网智能视频服务|
|iotid|iotid|IoT设备身份认证|
|isoc|isoc|IoT安全运营中心|
|isoc_fss|fss|IoT固件安全检测FSS|
|airec|airec|智能推荐|
|dlf|dlf|数据湖构建|
|datav|datav|DataV数据可视化|
|odps|odps|大数据计算服务|
|sc|stream|实时计算 Flink版|
|emapreduce|emr|E-MapReduce|
|graphcompute|graphcompute|图计算服务|
|datahub|dhs|数据总线|
|spark|ddi|数据洞察|
|ddicdp|cdp|企业数据云|
|brainindustrial|brain-industrial|工业大脑开放平台（公测中）|
|graphanalytics|iplus|关系网络分析|
|sls|log|日志服务|
|opensearch|opensearch|开放搜索|
|elasticsearch|elasticsearch|Elasticsearch|
|hologram|hologram|交互式分析|
|dide|dataworks,maxcompute|DataWorks|
|cdp|dataworks,maxcompute|数据集成 Data Integration|
|nodejs|npp|Node.js 性能平台|
|xtrace|xtrace|链路追踪|
|prometheus|arms|Prometheus监控服务|
|rdc|rdc|云效|
|mpaas|mpaas|移动开发平台 mPaaS|
|bpstudio|bpstudio|云速搭|
|sos|yundun-sos,mssp|安全管家|
|xianzhi|yundun-xianzhi|安全众测|
|sddp|yundun-sddp|数据安全中心|
|sas|yundun-sas,yundun-aegis,sasti|云安全中心（态势感知）|
|kms|kms|密钥管理服务|
|ram|ram,sts,ims|访问控制|
|cloudsso|cloudsso|云SSO|
|actiontrail|actiontrail|操作审计|
|bastionhost|yundun-bastionhost|堡垒机|
|pam|pam|特权访问服务|
|idaas|yundun-idaas|应用身份服务（IDaaS）|
|idaasauth|idaas-doraemon|安全认证服务 (IDAAS-Doraemon)|
|eiam|eiam|应用身份服务(EIAM2.0)|
|ddos|yundun-ddos|DDoS防护|
|gamebox|yundun-gamesecbox|DDoS防护|
|ddoscoo|yundun-high,yundun-ddoscoo|DDoS高防|
|gameshield|yundun-gameshield|游戏盾|
|cfw|yundun-cloudfirewall|云防火墙|
|uem|uem|终端访问控制系统|
|csas|csas|云安全访问服务|
|waf|yundun-waf|Web应用防火墙|
|afs|yundun-afs,afs|人机验证（数据风控）|
|cas|yundun-cert|数字证书管理服务（原SSL证书）|
|avds|yundun-avds|数字证书管理服务（原SSL证书）|
|lvwang|yundun-greenweb|内容安全|
|cloudauth|yundun-cloudauth|实人认证|
|antcloudauth|antcloudauth|金融级实人认证|
|saf|yundun-saf|风险识别|
|aegis|yundun-aegis|云安全中心（安骑士）|
|hsm|yundun-hsm|加密服务|
|dbaudit|yundun-dbaudit|数据库审计|
|acm|acmm,acm|云市场|
|quotas|quotas|配额中心|
|bss|bss,bssapi,efc|费用中心|
|notifications|notifications|消息中心|
|agency|agency|分销平台|
|beian|beian,bsn|备案|
|support|support,workorder-authorization|工单|
|pubdns|pubdns|公共DNS|
|netana|nis|网络智能服务|
|quickbi|quickbi|Quick BI|
|voicebot|voicebot|智能语音导航|
|cams|cams|ChatAPP 消息|
|xgip|xgip|5G互联平台|
|adcp|adcp|分布式云容器平台|
|hcs_hgw_cloudboxoss_public_cn|oss-cloudbox|云盒OSS存储|
|nlb|nlb|网络型负载均衡|
|ipv6gateway|vpc|IPv6 网关|
|cdt|cdt|云数据传输|
|fivegcc|fivegcc|云连接器(CC5G)|
|grafana|arms|Grafana服务|
|appstreaming|appstreaming|无影云应用|
|antppc|antppc|蚂蚁隐私计算服务平台|
|energyexpert|energy|能耗宝|
|linkedmall|linkedmall|企业商城(LINKEDMALL)|
|irs|irs|IP资源服务|
|autolearn|paiplugin|机器学习|
|ive|ive|智能短视频平台|
|avatar|avatar|虚拟数字人|
|watermark|lvwangwatermark|绿网数字水印|
|bccluster|eflo|智能计算灵骏|
|msha|msha|多活容灾MSHA|
|docmind|docmind|文档智能|
|eas|eas|模型在线服务|
|searchengine|searchengine|搜索引擎|
|nlstingwwu|tingwu|听悟服务|
|resourcecenter|resourcecenter|资源中心|
|atp|grace|应用诊断分析平台|
|datasetacc|datasetacc|PAI 数据集加速|
|dashscope|dashscope|模型服务灵积 dashscope|
|emrstarrocks|sr|EMR Serverless StarRocks|
|sfm|sfm,aimiaobi,dataanalysisgbi,aimiaodu,contactcenterai,bailiancontrol,bailiandata|专属大模型|
|ecs-workbench|ecs-workbench|ecs-workbench|
|elkxops|es-serverless|Elasticsearch服务化|
|acc|acc|容器计算服务 ACS|
|pop|AIDC-NBF|Pop网关|
|xingchen|xingchen|通义星尘|
|dashvector|dashvector|向量检索服务|
|yundun-antiddosbag|yundun-antiddosbag|云盾DDoS原生防护（Anti-DDoS Origin）|
|cro|cro|cro|
|ddosdiversion|ddosdiversion|DDoS原生代播|
|milvus|milvus|向量检索 Milvus 版|
|eduaiservice|eduaiservice|智作工坊|
|emr-serverless-spark|emr-serverless-spark|EMR Serverless Spark|
|emrspark|emr-serverless-spark|E-MapReduce Serverless Spark|
|mpbigdata|dataexchange|Data Exchange|
|EMASAppMonitor|emasha|EMAS移动监控|
|AppFlow|appflow|应用与数据集成平台|
|rai|rai|Responsible AI服务|
|documentAutoml|documentautoml|OCR文档自学习|
|imarketing|intelligent-creation|营销引擎云码|
|selectdb|selectdb|云数据库 SelectDB 版|
|ndr|yundun-ndr|NDR|
|dcdnservices|esa|边缘安全加速（ESA）|
|gwlb|gwlb|网关型负载均衡|
----
