version: '3'

# https://docs.docker.com/compose/compose-file/

services:
  my-nginx:
    image: nginx:1.13.1-alpine
    environment:
      A: AAA
    networks:
      - my-swarm-network
    ports:
      - 8088:80
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
networks:
  my-swarm-network:

