

* link:https://docs.docker.com/desktop/cert-revoke-solution/[Resolve the recent Docker Desktop issue on macOS]
如果出现这个 弹框报错 : "Malware Blocked: “com.docker.vmnetd” was not opened because it contains malware", 则按照该流程走一遍。

## 安装

[source,shell]
----
# 如果MacOS上安装后启动不起来，请参考下载使用这里提示的版本。比如：
# 比如: 2024-05-16, 安装 4.30.0 版本的 Mac with Intel chip 版本就启动不起来，退回成 4.26.0 版本就好了。
brew info docker

#brew install --cask docker
#brew uninstall docker

# 下载 Docker.dmg 后
vi ~/.zshrc  # 增加以下配置
export PATH="${HOME}/.docker/bin:${PATH}"


# 启动异常诊断
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose check
ll /usr/local/bin/dock*
ll ~/Library/Containers/com.docker.*
ll ~/Library/Containers/com.docker.docker/Data/log/host/

/Applications/Docker.app/Contents/Resources/bin/docker system prune --all --force
----

## 查看文件内容

* 方式1： 通过docker descktop 查看正在运行的 container 里的文件
* 方式2： 通过 `docker cp` 命令来检查docker镜像最终的某个文件的内容。示例：

[source,shell]
----
DOCKER_IMAGE=docker.io/otel/opentelemetry-collector-contrib:0.96.0
FILE_IN_IMAGE=//etc/otelcol-contrib/config.yaml

# 拉取最新Docker镜像
docker pull ${DOCKER_IMAGE}
# 创建临时 docker 容器
id=$(docker create ${DOCKER_IMAGE})
# 从 docker 容器中 copy 文件到 当前目录
cur_dir=$(pwd)
rm -fr /tmp/a
mkdir -p /tmp/a
cd /tmp/a
docker cp $id:${FILE_IN_IMAGE} .
# 删除临时 docker 容器
docker rm -v $id
cd ${cur_dir}
----




## ~/.docker/config.json

- link:https://docs.docker.com/engine/reference/commandline/cli/#docker-cli-configuration-file-configjson-properties[Docker CLI configuration file (config.json) properties]
- link:https://docs.docker.com/engine/reference/commandline/login/#credential-stores[Credential stores]
- link:https://www.passwordstore.org/[pass]

[source,shell]
----
brew install pass
----



`docker login` 如果这个错误，则修改 `vi ~/.docker/config.json` 删除 "credsStore"

[source,plain]
----
Error saving credentials: error storing credentials - err: exit status 1, out: `status code not OK but 500: {"message":"Post \"https://hub.docker.com/v2/users/login?refresh_token=true\": EOF"}
{"message":"Post \"https://hub.docker.com/v2/users/login?refresh_token=true\": EOF"}`
----

[source,shell]
----
{
  "credsStore": "osxkeychain"
}
----


## /etc/docker/daemon.json
## ~/.docker/daemon.json



## 镜像源

[source,shell]
----
# 安装 chsrc
brew install chsrc
# 列出 docker hub 的 镜像源
chsrc list docker
----

MacOS 的 Docker desktop ： Settings / Docker Engine 进行配置：

[source,json]
----
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "registry-mirrors": [
    "https://docker.1panel.live",
    "https://docker.m.daocloud.io",
    "https://huecker.io"
  ]
}
----

## 代理
参考 link:tinyproxy.adoc[tinyproxy]

注意：由于macos上的docker engine 实际也是运行在一个镜像里的，故代理服务器地址不能是 127.0.0.1，这里的30.166.33.108就是个人电脑（宿主机）的局域网IP。

[source,json]
----
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "proxies": {
    "http-proxy": "http://30.166.33.108:13660",
    "https-proxy": "http://30.166.33.108:13660",
    "no-proxy": "*.test.example.com,.example.org"
  }
}
----


## tag

[source,shell]
----
docker image tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]
docker image push IMAGE[:TAG]
----

## Manifest
* Docker Image Manifest V1 : ❌ 已废弃。 2017-02-28, Docker v1.13开始不再支持
* Docker Image Manifest V2 Schema1 : ❌ 已废弃。
  临时版本，且兼容V1。
* Docker Image Manifest V2 Schema2 :
  支持多架构，可内容寻址。
  可以通过 docker pull, docker push 即可升级到新版本。
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "mediaType": "application/vnd.docker.container.image.v1+json",
  "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",

* OCI 格式： 基于 Docker Image Manifest V2 Schema 2 改造。
  "mediaType": "application/vnd.oci.image.manifest.v1+json"
  "mediaType": "application/vnd.oci.image.config.v1+json"
  "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",

