

* link:http://projects.spring.io/spring-boot/#quick-start[reference guide]

## banner
默认打印 classpath下 banner.txt，可以修改文件位置和编码。
也可以是图片，图片的话会转为 https://en.wikipedia.org/wiki/ASCII_art[ASCII art]。

一些在线的 ASCII art 工具：
* [Text to ASCII Art Generator (TAAG)](http://www.patorjk.com/software/taag/)
* [1](http://ascii.mastervb.net/text_to_ascii.php)
* [2](http://chris.com/ascii/)
* [5 Best Ascii Art Generators (Convert your Image to Text)](http://www.mytrickpages.com/2013/10/5-best-ascii-art-generators-convert-your-image-to-text.html)


## gradle 启动多个 profile

[source,groovy]
----
# build.gradle
bootRun {
    String activeProfile =  System.properties['spring.profiles.active']
    String confLoc = System.properties['spring.config.location']
    systemProperty "spring.profiles.active", activeProfile
    systemProperty "spring.config.location", "file:$confLoc"
}

./gradlew -Dspring.profiles.active=a,b bootRun

# idea intellij 的 Run/Debug 中编辑窗口如下配置：
Tasks:              bootRun
VM options:         -Dspring.profiles.active=a,b
Script parameters:
----




## multiple layers

layerd 模式，不改改变 spring boot fat jar 包的目录格式
仍然是  `/`,  `BOOT-INF/classes`, `BOOT-INF/lib`  的目录结构。
仅仅增加了 `BOOT-INF/layers.idx`,
如果 includeLayerTools=true ，还 会增加 `BOOT-INF/lib/spring-boot-jarmode-layertools-3.2.2.jar`。


但是为了能复用 docker 的分层镜像能力，加快构建速度，故 按照配置 默认 将 完整 jar 包中的文件分成多个 逻辑上的layer，
并将分层信息写入到 BOOT-INF/layers.idx 中。
最后 通过  java -Djarmode=layertools -jar demo-0.0.1.jar extract

注意： includeLayerTools=true 时 fat jar 中会包含 `BOOT-INF/lib/spring-boot-jarmode-layertools-3.2.2.jar`

《link:https://www.baeldung.com/docker-layers-spring-boot[Reusing Docker Layers with Spring Boot]》
《link:Creating Docker Images with Spring Boot(https://www.baeldung.com/spring-boot-docker-images#layered-jars)》
  https://github.com/eugenp/tutorials/tree/master/docker-modules/docker-spring-boot

* 先 maven 打包
* 再 java -Djarmode=layertools -jar demo-0.0.1.jar extract  输出不同的 layer 目录，每个 layer 的根目录 都相当于 fat jar 内部的根目录
* Dockerfile:

[source,shell]
----
# 查看 jar 的 layers
java -Djarmode=layertools -jar demo-0.0.1.jar list
# 解压
java -Djarmode=layertools -jar demo-0.0.1.jar extract
----

## logging

* spring-boot-2.7.11.jar!/org/springframework/boot/logging/logback/defaults.xml
* spring-boot-2.7.11.jar!/org/springframework/boot/logging/logback/base.xml
* org.springframework.boot.logging.LoggingSystem
* org.springframework.boot.logging.LoggingSystem#get(java.lang.ClassLoader)
* org.springframework.boot.logging.LoggingSystemFactory  # 依次尝试使用 LogbackLoggingSystem.Factory, Log4J2LoggingSystem.Factory, JavaLoggingSystem.Factory
* org.springframework.boot.logging.AbstractLoggingSystem#getSpringConfigLocations # 拼接带 "-spring" 的log的配置文件名，比如: "logback-spring.xml"



## gradle plugin
* org.springframework.boot
** link:https://docs.spring.io/spring-boot/docs/3.1.4/gradle-plugin/reference/htmlsingle/[Spring Boot Gradle Plugin Reference Guide]
* io.spring.dependency-management

* org.springframework.boot.bom
** https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html#appendix.dependency-versions.properties[dependency-versions.html]
** https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/3.1.4/spring-boot-dependencies-3.1.4.pom[org.springframework.boot/spring-boot-dependencies/3.1.4/pom]
** https://github.com/spring-projects/spring-boot/blob/v3.1.4/spring-boot-project/spring-boot-dependencies/build.gradle[build.gradle]
** https://github.com/spring-projects/spring-boot/blob/9004966353e67765cbb369bed4ddc97817adf8ef/buildSrc/src/main/java/org/springframework/boot/build/bom/BomPlugin.java#L26[BomPlugin.java]
** https://github.com/spring-projects/spring-boot/blob/9004966353e67765cbb369bed4ddc97817adf8ef/buildSrc/src/main/java/org/springframework/boot/build/bom/BomExtension.java[BomExtension.java]
** https://github.com/spring-projects/spring-boot/blob/9004966353e67765cbb369bed4ddc97817adf8ef/buildSrc/src/test/java/org/springframework/boot/build/bom/BomPluginIntegrationTests.java[BomPluginIntegrationTests.java]
** https://github.com/spring-projects/spring-boot/blob/9004966353e67765cbb369bed4ddc97817adf8ef/buildSrc/build.gradle#L71[buildSrc/build.gradle]
* org.springframework.boot.conventions
* org.springframework.boot.deployed
* org.springframework.boot.gradle.tasks.bundling.BootJar#copy  # bootJar task 的入口
* org.springframework.boot.gradle.tasks.bundling.BootArchiveSupport
* org.springframework.boot.gradle.tasks.bundling.BootZipCopyAction#execute
* org.gradle.api.file.FileCopyDetails               # 哪里生成的？
* org.springframework.boot.loader.tools.layer.CustomLayers#selectLayer
* org.springframework.boot.gradle.tasks.bundling.BootArchive
* org.springframework.boot.gradle.plugin.JavaPluginAction#configureBootJarTask  // ⭕️⭕️⭕️ 配置 bootJar


[souce,shell]
----
bootJar.classpath = [ "/**/build/classes/java/main", "/**/build/resources/main", "/**/*.jar" ]
bootJar.source = [ "/**/build/tmp/bootJar/MANIFEST.MF", "/**/build/classes/java/main/**", "/**/build/resources/main/**", "/**/*.jar" ]


# 如果要将 BOOT-INF/classes 下的 部分 类移到 root , 可以用以下方式配置
tasks.named("bootJar") {
    // ...
    filesMatching("**/MyLoader*", { details ->
        println "=======88888 filesMatching : " \
            + "\n\t details                        =" + details \
            + "\n\t details.getRelativeSourcePath()=" + details.getRelativeSourcePath() \
            + "\n\t details.getRelativePath()      =" + details.getRelativePath()

        // relativeSourcePath = com/github/btpka3/first/spring/loader/MyLoaderMain.class
        // relativePath       = BOOT-INF/classes/com/github/btpka3/first/spring/loader/MyLoaderMain.class
        details.setRelativePath(details.getRelativeSourcePath());
    })
}
# 然后命令行执行（注意：一定要clean，gradle 有检查，无需copy时，触发不到上述chek）
./gradlew clean bootJar ; unzip -l build/libs/first-spring-loader-0.0.1-SNAPSHOT.jar | grep MyLoader
----


## pom.xml

.方式1： 做为parent

[source,xml]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.9.RELEASE</version>
</parent
----

.方式2： import bom
[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>1.0.0.RELEASE</version>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----



## version

[,cols="1,1,1,1,1,1,1,1,1"]
|===
| spring boot | spring framework | jdk | maven | gradle    | tomcat | jetty | undertow | servlet

|3.2.2        |6.1.3             |17   | 3.6.3 | 7.5       | 10.1   |12.0   |2.3    |6.0
|3.0.0        |6.0.2             |17   | 3.5   | 7.5       | 10.0   |11     |2.2    |5.0
|2.7.18       |5.3.31            |1.8  | 3.5   | 6.8 ~ 8.x | 9.0    | 10.0  | 2.0   |4.0
|2.0.0.RELEASE|5.0.4.RELEASE     |1.8  | 3.2   | 4         | 8.5    | 9.4   |1.4    |3.1
|1.5.9.RELEASE|4.3.13.RELEASE    |1.7  | 3.2   | 2.9       | 8      |9.3    |1.3    |3.1
|1.0.0.RELEASE|4.0.3.RELEASE     |1.6  | 3.0   | ?         | 8      |9      |?      |?

|===




## Actuator
Q. Endpoint vs.Controller


EndpointHandlerMappingCustomizer
org.springframework.boot.actuate.endpoint.web.EndpointMediaTypes
org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration
org.springframework.boot.actuate.autoconfigure.endpoint.EndpointAutoConfiguration
org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
org.springframework.beans.factory.ObjectProvider
org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration
No converter for [class org.springframework.boot.actuate.health.SystemHealth]


## gradle
### bootJar

[source,groovy]
----
tasks.named("bootJar") {

    // 将给定的 jar包 zip 展开到顶层
    from(zipTree((project.configurations.runtimeClasspath.find { it.name.startsWith("byte-buddy") } )))
    // 将给定的 jar包 zip 从fat jar的打包中移除
    filesMatching("byte-buddy-*.jar", { details ->
        // 不再copy该文件
        details.exclude()
    })

}
----

## BootstrapContext

- org.springframework.boot.BootstrapContext
- org.springframework.boot.BootstrapRegistry
- org.springframework.boot.ConfigurableBootstrapContext
- org.springframework.boot.DefaultBootstrapContext
- org.springframework.boot.BootstrapRegistryInitializer
- org.springframework.boot.SpringApplication#addBootstrapRegistryInitializer

## EnvironmentPostProcessor
org.springframework.boot.env.EnvironmentPostProcessor

## Scan

org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider
org.springframework.context.annotation.ClassPathBeanDefinitionScanner


## autoConfiguration
org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener



### Filter bean 自动被注册

- 参考：`org.springframework.boot.web.servlet.ServletContextInitializerBeans#addAdaptableBeans`
- 参考: link:https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-disable-registration-of-a-servlet-or-filter [Disable Registration of a Servlet or Filter]

解法
[source,java]
----
@Bean
public FilterRegistrationBean filterRegistrationBean() throws Exception {
    FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean();
    filterRegistrationBean.setEnabled(false);
    filterRegistrationBean.setFilter(authenticationTokenFilterBean());
    return filterRegistrationBean;
}
----


### META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.replacements
### META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

spring boot 3.4: 《link:https://docs.spring.io/spring-boot/reference/features/developing-auto-configuration.html#features.developing-auto-configuration.locating-auto-configuration-candidates[Creating Your Own Auto-configuration]》

相比 `META-INF/spring.factories` 的优点

* 按需加载
* 无反射操作
* 强类型检查

相关类:

. org.springframework.boot.autoconfigure.EnableAutoConfiguration#getCandidateConfigurations
. org.springframework.boot.autoconfigure.AutoConfigurationImportSelector
. org.springframework.boot.autoconfigure.AutoConfiguration        # spring boot 2.7 新增
. org.springframework.boot.context.annotation.ImportCandidates    # spring boot 2.7 新增, 加载 "META-INF/spring/%s.imports" 文件
. org.springframework.boot.autoconfigure.ImportAutoConfiguration

哪些扩展点使用该机制?

. org.springframework.boot.autoconfigure.AutoConfiguration
. interface org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration


[source,java]
----
package your.packages;
import org.springframework.boot.autoconfigure.AutoConfiguration;

@AutoConfiguration(  // ⭕️ 注意: 配置该注解
    beforeName = "org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration",
    afterName = "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
)
@ConditionalOnClass(Xxx.class)
public class MyAutoConfiguration {

	// Auto-configured beans ...

	@Configuration(proxyBeanMethods = false)
	@ConditionalOnClass(SomeService.class)
	public static class SomeServiceConfiguration {

		@Bean
		@ConditionalOnMissingBean
		public SomeService someService() {
			return new SomeService();
		}
	}
}
----

module-info.java
[source,java]
----
module your.packages {
    provides org.springframework.boot.autoconfigure.AutoConfiguration
        with your.packages.MyAutoConfiguration;
}
----


### META-INF/spring.factories 中的类没启动

* org.springframework.boot.autoconfigure.EnableAutoConfiguration
* org.springframework.boot.autoconfigure.AutoConfigurationImportSelector
* org.springframework.boot.autoconfigure.AutoConfiguration
* org.springframework.core.io.support.SpringFactoriesLoader#loadFactories 条件断点
* 开启 trace 日志
* 使用 META-INF/spring.factories 的不足
** 硬编码依赖：需要显式写明类的全限定名
** 类加载开销：启动时需要全量加载所有配置类
** Java模块化系统支持差。

[source,properties]
----
logging.level.org.springframework.core.io.support.SpringFactoriesLoader= TRACE
----

META-INF/spring.factories
----
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
  xxx.yyy.MyAutoConfiguration
----

MyAutoConfiguration.java
[source,java]
----
pakcage xxx.yyy;
@Configuration // ⭕️ 注意: 配置该注解
@ConditionalOnClass(Xxx.class)
public class MyAutoConfiguration {
   // ...
}
----


### META-INF/spring/aot.factories




### @ConditionalOnProperty 表达式不成立

- link:https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-troubleshoot-auto-configuration[Troubleshoot Auto-configuration]
- org.springframework.boot.autoconfigure.condition.ConditionEvaluationReport
- 开启 debug 日志

[source,properties]
----
logging.level.org.springframework.core.io.support.SpringFactoriesLoader= TRACE
----


## @ConfigurationProperties 的顺序？

- ConfigurationPropertiesBindingPostProcessor


## @Bean BeanFactoryPostProcessor 初始化
[source,java]
----
/**
 * 注意：这个是 BeanDefinitionRegistryPostProcessor，故
 * - 方法参数不能依赖 @ConfigurationProperties 类，因为它们尚未初始化好。
 * - 方法必须是 static 类型。否则会有初始化问题。
 */
@Bean
//@ConfigurationProperties("my.prefix") // 这个不管用
static MapperScannerConfigurer mapperScannerConfigurer(ConfigurableEnvironment env) {
    MapperScannerConfigurer mapperScannerConfigurer = new MapperScannerConfigurer();
    mapperScannerConfigurer.setSqlSessionFactoryBeanName("yourBeanName");
    ConfUtils.bind(env, "my.prefix", mapperScannerConfigurer);
    return mapperScannerConfigurer;
}
----

## @Value 中的占位符何时处理的？
- PropertySourcesPlaceholderConfigurer
-- 是 BeanFactoryPostProcessor
-- 最低优先级

- 可以通过 `ApplicationContext.getEnvironment().resolvePlaceholders("${x.zz:999}"` 来取值
- 可以通过 `new RelaxedDataBinder(environment.getPropertySources(), "spring.my").bind(new PropertySourcesPropertyValues(propertySources));` 来 binding 对象(Spring boot 1.x)

- org.springframework.core.env.SystemEnvironmentPropertySource#getProperty :
-- `.` 替换成 `_`
-- `-` 替换成 `_`
-- 转换成全大写

## 给 bean 起别名

[source,java]
----
/**
 * 起别名: jdbcTemplate -> jdbcTemplateSmeta
 *
 * @param reg
 */
@Autowired
public void test(ConfigurableBeanFactory reg) {
    reg.registerAlias("jdbcTemplate", "jdbcTemplateSmeta");
    reg.registerAlias("jdbcTemplate", "jdbcTemplateMtee");
}
----


## metrics

### 记录日志

- Meters

[source,java]
----
@Component
@ExportMetricWriter
public class MyMetricWriter implements MetricWriter, Closeable {

    private static final Log logger = LogFactory.getLog(MyMetricWriter.class);


    @Override
    public void increment(Delta<?> delta) {
        // record increment to log
    }

    @Override
    public void set(Metric<?> value) {
        // record set metric to log
    }

    @Override
    public void reset(String name) {
        // Not implemented
    }

    @Override
    public void close() {
    /// ...
    }
}
----


