



* link:https://github.com/cglib/cglib[cglib]
已经多年未更新,
Maven GAV : cglib:cglib
* Java Language Conversion Assistant (jCLA)


## JVM 指令
* link:https://docs.oracle.com/javase/specs/index.html[Java Language and Virtual Machine Specifications]

## ASM
* link:https://asm.ow2.io/[ASM]
API级别较低，


## commons-bcel
* link:https://commons.apache.org/proper/commons-bcel/[BCEL] Apache Byte Code Engineering Library
Maven GAV : org.apache.bcel:bcel
API 级别很低，直接面向 JVM 的指令集，比如
** org.apache.bcel.generic.ALOAD
** org.apache.bcel.generic.ICONST
** org.apache.bcel.generic.INVOKEVIRTUAL
** org.apache.bcel.generic.ARETURN


## bytebuddy
* link:https://bytebuddy.net/[ByteBuddy]

提供比较高级的API，类似spring 的AOP，直接直观编写相关代码

* net.bytebuddy.implementation.Implementation
** net.bytebuddy.implementation.MethodDelegation
** net.bytebuddy.asm.Advice

### bind.annotation
* net.bytebuddy.implementation.bind.annotation.Argument
[source,java]
----
package com.alibaba.code.u158230.mtee.scan.clazz.biz.service;
public class HelloDemo {

    public String hello(String name) throws ClassNotFoundException {
        return hello(name, false);
    }

    protected String hello(String name, boolean resolve)
            throws ClassNotFoundException {
        return "hello " + name + ", " + resolve;
    }
}
----

[source,java]
----
   @SneakyThrows
    public void agentmain(String agentArgs, Instrumentation inst) {
        new AgentBuilder.Default()
                .with(new MyListener())
                .type(named("com.alibaba.code.u158230.mtee.scan.clazz.biz.service.HelloDemo"))
                .transform((builder, typeDescription, classLoader, module, protectionDomain) ->
                        builder.method(named("hello").and(takesArguments(String.class)))
                                .intercept(MethodDelegation.to(HelloDemoInterceptor.class))

                )
                .installOn(inst);
    }
----


[source,java]
----
@SneakyThrows
public void agentmain(String agentArgs, Instrumentation inst) {
    public static String intercept(
            @AllArguments Object[] args,
            @Argument(0) String arg0,
            @This Object thisObject,
            @Origin Method targetMethod
    ) {
        return "AAA1:" + arg0 + ":BBB1";
    }
}
----


反编译后的代码

[source,java]
----
package com.alibaba.code.u158230.mtee.scan.clazz.biz.service;

import com.alibaba.code.u158230.mtee.scan.clazz.biz.service.load_class.HelloDemoInterceptor;
import java.lang.reflect.Method;

public class HelloDemo {
    private static final /* synthetic */ Method cachedValue$6BctlvEP$vhkilf2;

    static {
        ClassLoader.getSystemClassLoader().loadClass("net.bytebuddy.dynamic.Nexus").getMethod("initialize", Class.class, Integer.TYPE).invoke(null, HelloDemo.class, 232088493);
        cachedValue$6BctlvEP$vhkilf2 = HelloDemo.class.getMethod("hello", String.class);
    }

    public String hello(String string) throws ClassNotFoundException {
        return HelloDemoInterceptor.intercept(
            (Object[])new Object[]{string},          // @AllArguments Object[] args,
            (String)string,                          // @Argument(0) String arg0,
            (Object)this,                            // @This Object thisObject,
            (Method)cachedValue$6BctlvEP$vhkilf2     // @Origin Method targetMethod
            );
    }

    protected String hello(String name, boolean resolve) throws ClassNotFoundException {
        return "hello " + name + ", " + resolve;
    }

    private /* synthetic */ String hello$original$5jAYS18N(String name) throws ClassNotFoundException {
/*10*/         return this.hello(name, false);
    }
}


----







* net.bytebuddy.implementation.bind.annotation.AllArguments
* net.bytebuddy.implementation.bind.annotation.This
* net.bytebuddy.implementation.bind.annotation.Super

[source,java]
----
package com.alibaba.code.u158230.mtee.scan.clazz.biz.service;

import com.alibaba.code.u158230.mtee.scan.clazz.biz.service.HelloDemo$auxiliary$R3Gxfb9R;
import com.alibaba.code.u158230.mtee.scan.clazz.biz.service.load_class.HelloDemoInterceptor;

public class HelloDemo {
    static {
        ClassLoader.getSystemClassLoader().loadClass("net.bytebuddy.dynamic.Nexus").getMethod("initialize", Class.class, Integer.TYPE).invoke(null, HelloDemo.class, 1611194228);
    }

    final /* synthetic */ Object clone$accessor$ckL1ZVd6() throws CloneNotSupportedException {
        return super.clone();
    }

    private /* synthetic */ String hello$original$dqVjyLaG(String name) throws ClassNotFoundException {
/*10*/         return this.hello(name, false);
    }

    final /* synthetic */ boolean equals$accessor$ckL1ZVd6(Object object) {
        return super.equals(object);
    }

    final /* synthetic */ int hashCode$accessor$ckL1ZVd6() {
        return super.hashCode();
    }

    final /* synthetic */ String toString$accessor$ckL1ZVd6() {
        return super.toString();
    }

    protected String hello(String name, boolean resolve) throws ClassNotFoundException {
        return "hello " + name + ", " + resolve;
    }

    public String hello(String string) throws ClassNotFoundException {
        new HelloDemo$auxiliary$R3Gxfb9R().target = this;
        return HelloDemoInterceptor.intercept(
            (Object[])new Object[]{string},
            (String)string,
            (Object)this,
            (Object)new HelloDemo$auxiliary$R3Gxfb9R()   // @Super 的实现
        );
    }
}
----

[source,java]
----
package com.alibaba.code.u158230.mtee.scan.clazz.biz.service;

import com.alibaba.code.u158230.mtee.scan.clazz.biz.service.HelloDemo;
import sun.reflect.ReflectionFactory;

class HelloDemo$auxiliary$R3Gxfb9R {
    public volatile HelloDemo target;

    public boolean equals(Object object) {
        return this.target.equals$accessor$ckL1ZVd6(object);
    }

    public String toString() {
        return this.target.toString$accessor$ckL1ZVd6();
    }

    public int hashCode() {
        return this.target.hashCode$accessor$ckL1ZVd6();
    }

    protected Object clone() throws CloneNotSupportedException {
        return this.target.clone$accessor$ckL1ZVd6();
    }

    static HelloDemo$auxiliary$R3Gxfb9R make() {
        return (HelloDemo$auxiliary$R3Gxfb9R)ReflectionFactory.getReflectionFactory().newConstructorForSerialization(HelloDemo$auxiliary$R3Gxfb9R.class, Object.class.getDeclaredConstructor(new Class[0])).newInstance(new Object[0]);
    }
}
----

* net.bytebuddy.implementation.bind.annotation.Origin
* net.bytebuddy.implementation.bind.annotation.SuperCall

[source,java]
----
package com.alibaba.code.u158230.mtee.scan.clazz.biz.service;

import com.alibaba.code.u158230.mtee.scan.clazz.biz.service.HelloDemo$auxiliary$DdaGQyE2;
import com.alibaba.code.u158230.mtee.scan.clazz.biz.service.load_class.HelloDemoInterceptor;
import java.util.concurrent.Callable;

public class HelloDemo {
    static {
        ClassLoader.getSystemClassLoader().loadClass("net.bytebuddy.dynamic.Nexus").getMethod("initialize", Class.class, Integer.TYPE).invoke(null, HelloDemo.class, 800179506);
    }

    private /* synthetic */ String hello$original$0NpRpeEb(String name) throws ClassNotFoundException {
/*10*/         return this.hello(name, false);
    }

    protected String hello(String name, boolean resolve) throws ClassNotFoundException {
        return "hello " + name + ", " + resolve;
    }

    public String hello(String string) throws ClassNotFoundException {
        return HelloDemoInterceptor.intercept(
            (Callable)new HelloDemo$auxiliary$DdaGQyE2(this, string)  // ⭕️ @SuperCall Callable<String> superCall
        );
    }

    final /* synthetic */ String hello$original$0NpRpeEb$accessor$65HMLvGk(String string) throws ClassNotFoundException {
        return this.hello$original$0NpRpeEb(string);
    }
}
----

[source,java]
----
package com.alibaba.code.u158230.mtee.scan.clazz.biz.service;

import com.alibaba.code.u158230.mtee.scan.clazz.biz.service.HelloDemo;
import java.util.concurrent.Callable;

class HelloDemo$auxiliary$DdaGQyE2 implements Runnable, Callable {

    private HelloDemo argument0;
    private String argument1;

    public Object call() throws Exception {
        return this.argument0.hello$original$0NpRpeEb$accessor$65HMLvGk(this.argument1);
    }

    HelloDemo$auxiliary$DdaGQyE2(HelloDemo helloDemo, String string) {
        this.argument0 = helloDemo;
        this.argument1 = string;
    }

    @Override
    public void run() {
        this.argument0.hello$original$0NpRpeEb$accessor$65HMLvGk(this.argument1);
    }
}
----

* net.bytebuddy.implementation.bind.annotation.DefaultCall
是指调用 interface 的 默认实现的方法体。

* net.bytebuddy.implementation.bind.annotation.Pipe
* net.bytebuddy.implementation.bind.annotation.Empty
方法参数的默认值。比如 0, null, false

* net.bytebuddy.implementation.bind.annotation.SuperMethod
[source,java]
----
package com.alibaba.code.u158230.mtee.scan.clazz.biz.service;

import com.alibaba.code.u158230.mtee.scan.clazz.biz.service.load_class.HelloDemoInterceptor;
import java.lang.reflect.Method;

public class HelloDemo {
    private static final /* synthetic */ Method cachedValue$5VJiziI8$p196st0;

    static {
        ClassLoader.getSystemClassLoader().loadClass("net.bytebuddy.dynamic.Nexus").getMethod("initialize", Class.class, Integer.TYPE).invoke(null, HelloDemo.class, 543882062);
        cachedValue$5VJiziI8$p196st0 = HelloDemo.class.getDeclaredMethod("hello$original$elCNjqPk$accessor$5VJiziI8", String.class);
    }

    public final /* synthetic */ String hello$original$elCNjqPk$accessor$5VJiziI8(String string) throws ClassNotFoundException {
        return this.hello$original$elCNjqPk(string);
    }

    public String hello(String string) throws ClassNotFoundException {
        return HelloDemoInterceptor.intercept(
            (Method)cachedValue$5VJiziI8$p196st0  // @SuperMethod Method superMethod
        );
    }

    protected String hello(String name, boolean resolve) throws ClassNotFoundException {
        return "hello " + name + ", " + resolve;
    }

    private /* synthetic */ String hello$original$elCNjqPk(String name) throws ClassNotFoundException {
/*10*/         return this.hello(name, false);
    }
}
----










## Javassist
* link:https://www.javassist.org/[Javassist]

面向 `javassist.CtClass`,`javassist.CtMethod` 对象编程器。需要使用其特定的模板语言进行代码修改。

示例：

代码
[source,java]
----
ClassPool pool = ClassPool.getDefault();
CtClass cc = pool.get("Point");
CtMethod m = cc.getDeclaredMethod("move");
m.insertBefore("{ System.out.println($1); System.out.println($2); }");
cc.writeFile();
----

替换前
[source,java]
----
class Point {
    int x, y;
    void move(int dx, int dy) { x += dx; y += dy; }
}
----
替换后
[source,java]
----
class Point {
    int x, y;
    void move(int dx, int dy) {
        { System.out.println(dx); System.out.println(dy); }
        x += dx; y += dy;
    }
}
----
