== 概念
双亲委派
- 找类: 优先从父 classLoader 找
- 加载: 优先从父 classLoader 加载，加载不到再从自己找

== class lifecycle
https://www.artima.com/insidejvm/ed2/lifetype.html

[source,plain]
----
loading-> linking-> initialization->unloading.
在使用一个class前，需要以下步骤都完成，每个步骤都会申请内存：
1. The classes bytecodes need to be loaded and linked to resolve any static dependencies on other classes.
    - loading : 将字节码从外部（比如磁盘上）加载到 JVM 内存中.
    - linking : 将字节码数据与JVM运行态数据 merge。 又细拆分成以下几个步骤:
        - verification
        - preparation
        - resolution
1. The class needs to be initialized.
1. An instance of the class needs to be created.
----



== 通用
[source,plain]
----
# JDK8
bootstrap class loader                  # null : 加载 jvm核心类，比如 ${JRE_HOME}/lib/ 下的 jar，比如：rt.jar,resoures.jar, charasets.jar 等
  - sun.misc.Launcher$ExtClassLoader    # 加载 ${JRE_HOME}/lib/ext/ 下的 jar 包
    - sun.misc.Launcher$AppClassLoader  # 加载当前classPath下所有类

# JDK9
bootstrap class loader
  - jdk.internal.loader.ClassLoaders$PlatformClassLoade
    - jdk.internal.loader.ClassLoaders$AppClassLoader

--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED

----

== tomcat
- Apache Tomcat 9 : [Class Loader How-To](https://tomcat.apache.org/tomcat-9.0-doc/class-loader-howto.html)


CommonClassLoader               # tomcat通用类加载器：加载 ${catalina.base}/lib、${catalina.home}/lib 下的jar
SharedClassLoader               # tomcat共享类加载器：多个war包共享的类，由 conf/catalina.properties 中的 shared.loader 指定
CatalinaClassLoader             # tomcat
CatalinaClassLoader             #
WebAppClassLoader


[source,plain]
----
       Bootstrap(null)
          |
      Extention(jdk.internal.loader.ClassLoaders$PlatformClassLoader)
          |
         Common
          /    \
      Server   Shared
                /    \
            WebApp1  WebApp2
----


== pandora

- LaunchedURLClassLoader  #
- ModuleClassLoader      # pandora 的插件模块的classloader，负责隔离加载各个pandora插件下的类
- ReLaunchMainLauncher   #



[source,plain]
----
                  Bootstrap(null)
                   /    \                             \              \
         Application   PandoraContainerClassLoader    Module1(HSF) Module1(Metaq)
            |
            |
            |
    ReLaunchURLClassLoader   # 使用了 PandoraContainerClassLoader暴露的 classCache  ,
            |                # 起独立线程运行，使用该classLoader, 并运行 spring
            |
            |
    SpringBootApplicaiton#main

----




== Class#getDeclaredMethods 会触发 代码中 throw 的class 的类加载

[source,java]
----
package com.alibaba.security.gong9.mw.commons.utils;

import com.alibaba.security.gong9.mw.commons.Gong9MwException;

/**
 * @author dangqian.zll
 * @date 2023/7/3
 */
public class Aaa {

    public void sayHi() {
        TcclUtils.withTccl(() -> {
            throw new Gong9MwException("aaa", "aaa");
        });
    }
}
----

[source,java]
----
package com.alibaba.security.gong9.mw.commons.utils;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;

public class ClassLoaderTest {

    /**
     * 指定 jvm 参数： -verbose:class 并运行。
     */
    @Test
    public void testClassLoad01() {
        System.out.println("-------------------------- 1");
        // Aaa class 将会在此时被触发加载，但内部使用到的 TcclUtils, Gong9MwException 此时不会被触发加载
        Aaa o = new Aaa();
        System.out.println("-------------------------- 2");
        // 当使用反射获取相关声明的方法时，此时会触发 Gong9MwException 的类加载，但不会触发 TcclUtils 的类加载。
        Method[] methods = o.getClass().getDeclaredMethods();
        System.out.println("-------------------------- 3");
    }
}
----


[,cols="1,2"]
.classloader
|===
| cl | clClass

|ClassLoader.getPlatformClassLoader()
|"jdk.internal.loader.ClassLoaders$PlatformClassLoader"

|ClassLoader.getSystemClassLoader()
|""
|===



== 如何及时释放？
* ✅ 必须做的
** 为每个会话/用户创建独立的 ClassLoader，不要复用
** 定期清理不再使用的 ClassLoader（如会话超时）
** 显式调用 ClassLoader.close()（Java 7+）
** 清理 ThreadLocal（特别是线程池场景）
** 使用 WeakReference 缓存 Class 对象
** 设置合理的 JVM 参数：-XX:+ClassUnloading -XX:+UseG1GC

*  ❌ 避免做的
** 不要将用户定义的类引用放到静态变量中
** 不要在全局缓存中保存 ClassLoader 的引用
** 不要让线程池线程持有 ClassLoader 的引用
** 不要使用强引用缓存动态加载的类, 比如通过反射获取Method等对象，并保持强引用
** 避免 ThreadLocal 强引用，不清理。


[source,java]
----
public class ClassLoaderMonitor {
    public static void checkClassLoaderLeak() {
        // 使用 Java Management API 检查
        ClassLoadingMXBean loadingBean = ManagementFactory.getClassLoadingMXBean();
        System.out.println("Loaded class count: " + loadingBean.getLoadedClassCount());
        System.out.println("Total loaded class count: " + loadingBean.getTotalLoadedClassCount());
        System.out.println("Unloaded class count: " + loadingBean.getUnloadedClassCount());
    }

    // 使用 VisualVM 或 JConsole 分析堆内存
    // 查找 ClassLoader 实例数量和类型
}
----

类卸载的核心条件
Java 中类和 ClassLoader 能被卸载，必须同时满足以下条件：

1. ClassLoader 实例没有任何强引用
所有对该 ClassLoader 的引用必须都被清除
常见泄漏点：静态集合、ThreadLocal、缓存

2. 该 ClassLoader 加载的所有 Class 实例无强引用
加载的类对象实例、Class 对象本身都不能有强引用
包括反射缓存、动态代理等

3. 触发 GC
在满足前两个条件后，需要调用 System.gc() (FullGC) 或等待 JVM 自动 GC
