
* logback 1.3.x+ 要使用 slf4j 2.0+， 需要 spring boot 3.x 才可以使用。

## 参考
* link:https://github.com/qos-ch/logback[qos-ch/logback]


## 变量

logback.xml

[source,xml]
----
<property resource="application.properties" />
----


## conditional config

* link:https://janino-compiler.github.io/janino/#getting_started[Janino]
* link:https://github.com/qos-ch/logback/blob/1.1.11/logback-core/src/main/java/ch/qos/logback/core/joran/conditional/PropertyWrapperForScripts.java[PropertyWrapperForScripts]



## 使用 spring placeholder

* org.springframework.boot.logging.AbstractLoggingSystem
   #getSpringConfigLocations  在标准配置文件的基础上，还通过增加 "-spring" 关键来查找相关配置文件，比如 "logback-spring.xml".
* org.springframework.boot.logging.logback.LogbackLoggingSystem#getStandardConfigLocations
  默认使用 "logback-test.groovy", "logback-test.xml", "logback.groovy", "logback.xml" 进行初始化。
* org.springframework.boot.context.logging.LoggingApplicationListener
* org.springframework.boot.SpringApplicationRunListener
* org.springframework.boot.logging.AbstractLoggingSystem#getSpringInitializationConfig
* link:https://reflectoring.io/profile-specific-logging-spring-boot/[Using Profiles in logback-spring.xml]


logback-spring.xml 文件

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <springProperty name="destination" source="my.loggger.extradest"/>

  <springProfile name="dev">
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
      <encoder>
        <pattern>
          %d{HH:mm:ss.SSS} | %5p | %logger{25} | %m%n
        </pattern>
        <charset>utf8</charset>
      </encoder>
    </appender>

    <root level="DEBUG">
      <appender-ref ref="CONSOLE"/>
    </root>
  </springProfile>

  <springProfile name="staging">
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
      <encoder>
        <pattern>
          %d{yyyy-MM-dd};%d{HH:mm:ss.SSS};%t;%5p;%logger{25};%m%n
        </pattern>
        <charset>utf8</charset>
      </encoder>
    </appender>

    <root level="DEBUG">
      <appender-ref ref="CONSOLE"/>
    </root>
  </springProfile>

</configuration>
----

## ShutdownHook

* 相关类
** ch.qos.logback.core.joran.action.ShutdownHookAction
** ch.qos.logback.core.hook.DelayingShutdownHook

[source,xml]
----
<?xml version="1.0"?>
<configuration debug="true">
    <shutdownHook class="ch.qos.logback.core.hook.DefaultShutdownHook" />
</configuration>
----



## AsyncAppender

[source,shell]
----
# 检查 logback 等静态绑定类的加载的jar包位置
ognl -c 32ac360d '@org.slf4j.impl.StaticLoggerBinder@class.getProtectionDomain().codesource'
# 检查 ROOT logger 的 appender 列表
ognl -c 32ac360d '@org.slf4j.LoggerFactory@getLogger("ROOT").aai'
ognl -c 32ac360d '@org.slf4j.LoggerFactory@getLogger("ROOT").aai'
ognl -c 32ac360d '@org.slf4j.LoggerFactory@getLogger("ROOT").aai.getAppender("xxxAsyncAppender").blockingQueue.size()'
ognl -c 32ac360d '@org.slf4j.LoggerFactory@getLogger("ROOT").aai.getAppender("xxxAsyncAppender").blockingQueue.remainingCapacity()'
# 检查给定异步appender 的内部 worker 线程的状态。
ognl -c 32ac360d '@org.slf4j.LoggerFactory@getLogger("ROOT").aai.getAppender("xxxAsyncAppender").worker.getState()'
ognl -c 32ac360d '@org.slf4j.LoggerFactory@getLogger("ROOT").aai.getAppender("xxxAsyncAppender").worker.getStackTrace()'

----

## StatusListener

[source,shell]
----
# 输出logback 内部状态
ognl -c 6dfba8fd  -x 3 '
#context=new java.util.HashMap(),
#context.put("appKey","xx"),
#context.put("appSecret","xx"),

#openId="4398621042106",

@com.alibaba.security.uniface.i18n.ApplicationContextHolder@applicationContext
     .getBean(@com.taobao.baichuan.openaccount.api.OpenAccountQueryService@class)
     .getOpenAccountById(#context,#openId)
'
----


## LoggerContextListener





## 常用pattern格式定义

[source,plain]
----
%date{ISO8601}|%thread|%level|%logger|%msg%n
----


## 条件配置

* link:https://logback.qos.ch/manual/configuration.html[Conditional processing of configuration files]
* ch.qos.logback.core.joran.conditional.IfAction
* link:https://github.com/qos-ch/logback/blob/69ce513bdccc002a7fc4920ab6b7b373c593d2ff/logback-core/src/main/java/ch/qos/logback/core/joran/conditional/PropertyWrapperForScripts.java#L35[ch.qos.logback.core.joran.conditional.PropertyWrapperForScripts]

[source,java]
-----
public class PropertyWrapperForScripts {

    public boolean isNull(String k);

    public boolean isDefined(String k);

    public String p(String k);

    public String property(String k);
}
-----




## 如何确认哪些appender 输出了统一个
