

* link:https://micrometer.io/[micrometer]
** link:https://docs.micrometer.io/micrometer/reference/concepts/rate-aggregation.html[Rate Aggregation]
* link:https://github.com/micrometer-metrics/context-propagation[context-propagation]
* link:https://openmetrics.io/[OpenMetrics]
* link:https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md[OpenMetrics.md]
* link:https://quarkus.io/guides/telemetry-micrometer-tutorial[COLLECT METRICS USING MICROMETER]
* link:https://github.com/LatencyUtils/LatencyUtils[LatencyUtils]


## 如何查看结果


* Grafana
** link:https://grafana.com/grafana/dashboards/4701-jvm-micrometer/[JVM (Micrometer)]





## 数据类型
### Counter
### FunctionCounter
是一种特殊的counter，只增不减。


### Gauge
### TimeGauge
是一种特殊的 gauge，其值是 时间的值, 其有个 TimeUnit 的单位。
在采集的时候，会按照 MeterRegistry 的配置转换成对应的时间单位的数值。
### MultiGauge
是一种特殊的 gauge。当数据源是一个List时，可通过注册一个转换代码，一次性输出 不同tag值的 gauge.

### Timer
用于记录短时任务的次数和时长。

参考 `@TimedAspect`,`@Timed`,  `MeterTagAnnotationHandler`
### FunctionTimer

是一种特殊的Timer，只增不减。


### LongTaskTimer
长时间运行的任务，相比 Timer 只记录次数和时长，
LongTaskTimer 记录 活动的任务数量，活动任务的总耗时， 活动任务的最大耗时。 注意：LongTaskTimer不输出已完结任务的数量。



### DistributionSummary

内部有 count, total 数据字段.

## 直方图和百分比

* 百分比直方图
方法: io.micrometer.core.instrument.DistributionSummary.Builder#publishPercentiles


* 客户端百分比
方法: io.micrometer.core.instrument.DistributionSummary.Builder#publishPercentileHistogram()
百分比计算是在客户端（调用方的JVM上）计算的，然后直接可获取统计后的百分比，但无法再多实例，多tag做汇总聚合。



## MeterRegistry

* io.micrometer.core.instrument.simple.SimpleMeterRegistry
* io.opentelemetry.instrumentation.micrometer.v1_5.OpenTelemetryMeterRegistry
* io.micrometer.prometheus.PrometheusMeterRegistry
* org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusMetricsExportAutoConfiguration
* org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint
  注意：该 endpoint 是 给 Prometheus 拉取数据用的，故不要手动去curl访问该URL，访问一次就指针往前移动一次，Prometheus 拉取的数据就或少一点。
* io.micrometer.core.instrument.push.PushMeterRegistry
** io.micrometer.core.instrument.logging.LoggingMeterRegistry


## 示例

### 最大延迟

[source,java]
----
@Test
@SneakyThrows
public void testMaxDelay() {
    MeterRegistry registry = null;
    MaxDelayPerSecond obj = new MaxDelayPerSecond();
    registry.gauge(
            "example.gauge2",
            Tags.of("k2", "v2"),
            obj,
            MaxDelayPerSecond::getMaxDelay
    );

}

public static class MaxDelayPerSecond {
    long second;

    long maxDelay;

    protected void resetIfNecessary() {
        long s = System.currentTimeMillis() / 1000;
        if (s != second) {
            second = s;
            maxDelay = 0;
        }
    }

    public void record(long delay) {
        resetIfNecessary();
        if (delay > maxDelay) {
            maxDelay = delay;
        }
    }
    public double getMaxDelay() {
        resetIfNecessary();
        return maxDelay;
    }
}
----

### trace日志
等同于使用counter

### stat日志
等同于使用counter







