


## 总结

* mockito 是通过动态创建子类的方式来进行 mock的，所以 不支持 mock final 方法，不支持 mock private 方法。如果发现无法使用 mockito 测试的场景，请考虑重构代码。
* import static org.mockito.Mockito.*; 该 package 中提供了不少常用的静态测试方法。
* mockito link:https://asolntsev.github.io/en/2020/07/11/mockito-static-methods/[支持静态方法 mock]， link:https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#static_mocks[Mocking static methods]







### 使用 mockito 的注解

[source,java]
----
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Spy;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public class XxxServiceTest {
    /**
	 * 被测试的目标类。
	 */
    @Spy              // 表示 mock 部分方法。
    @InjectMocks      // 表示其他 `@Mock` 的对象都自动注入到 该测试目标中
    XxxService xxxService;

    @Mock             // 表示 完全 mock 掉该类
    YyyService yyyService;

    @Test
    public void test01(){
	    // mock 掉 被 `@Mock` 的类的方法
	    {
	        AccountInfoDO accountInfoDO = new AccountInfoDO();
	        when(yyyService.getUserInfo(anyLong()))
                .thenReturn(accountInfoDO);
	    }
	    // 部分 mock 被 `@Spy` 的类的方法
	    {
            List<String> authorities = Arrays.asList("AAA", "BBB");
            doReturn(authorities)
                .when(xxxService)
                .getAuthorities(anyString());
        }
	    // 单测目标方法
	    UserDetails userDetails = xxxService.loadUserByUsername("zhang3");
	    // ...
	}
}
----

### mock 被测试类中的其他方法
假如被测试类为：

[source,java]
----
public class XxxApi {
    private HttpServletRequest request;
    public Result doSaveOne() {
	    // ...
	    DictEventDO destEvent = checkEvent(destEventCode);
	    // ...
	}

    DictEventDO checkEvent(String eventCode) {
	    // ...
	}
}
----

TODO : 使用spring提供的mock类
下面演示如何使用mockito来mock：如何 mock 掉对 checkEvent 的调用

[source,java]
----
@Test
public void test(){
    // 通过 spy 方法，可部分mock 其相关方法
    XxxApi api = spy(new XxxApi());

    // mock 掉 XxxApi 中的 checkEvent 方法
    doReturn(null)
        .when(api)
        .checkEvent(any());

    // 测试 EventMappingOneApi 的 doSaveOne 方法（它内部调用了 checkEvent）
    api.doSaveOne();
}
----


### mock 被测试类中依赖的其他Service 的方法

假如被测试类为：
[source,java]
----
public class XxxApi {
    private HttpServletRequest request;
    public Result doSaveOne() {
	    // ...
	    String json = IOUtils.toString(request.getInputStream(), "UTF-8");
	    // ...
	}
}
----

下面代码可以 要 mock 掉 request.getInputStream


[source,java]
----
@Test
public void test(){

    // 为了简化，这里使用 spy 一下
    XxxApi api = spy(new XxxApi());

    // 创建 mock
    HttpServletRequest request = mock(HttpServletRequest.class);

    // spring-test 提供的工具类，可以修改被测试对象的成员字段（可以没有setter）
    ReflectionTestUtils.setField(
        api,
        "request",
        request
    );

    // mock 掉 `request.getInputStream` 的返回值
    // 复杂格式的内容，建议都放到 和被测试类平级的 外部文件中 `src/test/resources/../*`
    InputStream inputStream = XxxApi.class.getResourceAsStream("XxxApi-save01.json");
    when(request.getInputStream())
        .thenReturn(new DelegatingServletInputStream(inputStream));

    api.doSaveOne();
}
----

### ArgumentMatcher 示例
有些时候， mock 方法的返回值时，我们需要根据不同参数，返回不同的值。

* 单测示例0： 要测试的代码是N次循环调用，只想特定参数返回某个返回值，其他返回空list

测试代码

[source,java]
----
        when(getPermissionsOp.getPermissions(any(), any(), any(), any()))
            .thenAnswer(answer -> {
                if (Objects.equals(AuthorityCodeEnum.XXX.getCode(), answer.getArgument(1))
                    || Objects.equals(AuthorityCodeEnum.YYY.getCode(), answer.getArgument(1))) {
                    Set<String> set = new HashSet<>();
                    set.add(PermissionCodeEnum.ZZZ.getCode());
                    return set;
                } else {
                    return Collections.emptySet();
                }
            });
----

* 单测示例1：
被测试代码：

[source,java]
----
public class AaaService {
    private Bbb bbbService;
    public Result doSaveOne() {
	    // ...
	    Cursor cursor1 = bbbDao.query(map1, 1L, bean1);
	    StreamSupport.stream(it.spliterator(), false)...;
	    // ...
	    Cursor cursor2 = bbbDao.query(map2, 2L, bean2);
	    StreamSupport.stream(it.spliterator(), false)...;
	    // ...
	}
}
----
测试代码：

[source,java]
----
@Test
public void test(){
    // ...
   	{
        Cursor cursor = mock(Cursor.class);
        when(bbbDao.query(
	  	    argThat(map->map.size()==1),  // 来判断方法是否匹配，PS：可以对参数再加工
		    eq(1L),
		    any()
	    ))
	        .thenReturn(cursor1);
        when(cursor.spliterator())
            .thenReturn(Array.asList(1,2,3).spliterator());
    }
   	{
        Cursor cursor = mock(Cursor.class);
        when(bbbDao.query(
	  	    argThat(map->map.size()==1),
		    eq(2L),
		    any()
	    ))
	        .thenReturn(cursor1);
        when(cursor.spliterator())
            .thenReturn(Array.asList(4,5,6).spliterator());
    }
    // ...
}
----


### 被 mock 的方法有修改参数（比如 Set)

有时候，被测试的方法，会修改参数，尤其参数是 List/Set/Map 等 情形。
可以通过 doAnswer() 模拟 对参数的修改。

[source,java]
----
public class AaaService {
    private Bbb bbbService;
    public boolean getAppGroupsNext(String str, Integer page, Set<String> resultSet) {
	    // ...
	    resultSet.add("111");
	    // ...
	}
}
----
测示例：
[source,java]
----
@Test
public void test(){
    // ...
    doAnswer(invocation -> {
            Set<String> set = invocation.getArgument(0);
            set.add("mtee3.sync.taohost");
            return false;
        })
            .when(aaaService)
            .getAppGroupsNext(anyString(), any(), any());
    // ...
}
----


### mock 无返回值的方法

[source,java]
----
        doAnswer(answer -> {
            ((AuthAclOidDO) answer.getArgument(0)).setId(12L);
            return null;
        })
            .when(authAclOidDao)
            .insert(any());
----

### mock final 方法

参考：《link:https://www.baeldung.com/mockito-final[Mock Final Classes and Methods with Mockito]》、《link:https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#unmockable[What's new in Mockito 2]》

只需要 创建文件 `src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker`， 其文件内容只需包含一行 "mock-maker-inline" 即可。

可能引发的问题： 《link:https://github.com/mockito/mockito/issues/2082['this' is not available - when enabling mock-maker-inline]》, 且会造成debug 时找不到方法参数，造成NPE。 FIXME: 该case 在使用 3.8.0 版本 有遇到，升级到  3.11.2 后解决。


### mock 静态方法

意：需要maven 依赖  org.mockito:mockito-inline.
注意：这种方式是将整个类都mock掉的，无法做到类似 @Spy 那样部分方法才mock。故不适用于 单个类内部 静态方法A 调用 静态方法 B， 想仅仅测试A，而mock掉B 的case。

[source,java]
----
try(MockedStatic<XxxClass> theMock = Mockito.mockStatic(XxxClass.class)){
	theMock.when(XxxClass::xxxMethod).thenReturn("aaa");
	Assertions.assertEquals("aaa", XxxClass.xxxMethod());
}
----

有参数、有返回值的静态方法
[source,java]
----
try(MockedStatic<XxxClass> theMock = Mockito.mockStatic(XxxClass.class)){
	theMock.when(()->XxxClass.xxxMethod(any(),anyInt())).thenReturn("aaa");
	Assertions.assertEquals("aaa", XxxClass.xxxMethod());
}
----

### mock java.lang.System 相关方法

参考：《link:https://www.baeldung.com/java-system-stubs[Guide to the System Stubs Library]》、 三方库 ： link:https://github.com/webcompere/system-stubs[system-stubs]

[source,java]
----
public class EnvUtils {
    @Nullable
    public static String getAppName() {
        String value = System.getenv("APP_NAME");
        if(value!=null){
            return value
        }
        value = System.getenv("project.name");
        if(value!=null){
            return value
        }
        return System.getenv("spring.application.name");
    }
}
----

示例的单测代码：

[source,java]
----
import lombok.SneakyThrows;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import uk.org.webcompere.systemstubs.environment.EnvironmentVariables;
import uk.org.webcompere.systemstubs.properties.SystemProperties;
import uk.org.webcompere.systemstubs.resource.Resources;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static uk.org.webcompere.systemstubs.SystemStubs.withEnvironmentVariable;
public class EnvUtilsTest {
    @SneakyThrows
    @Test
    public void getAppName04() {
        Resources.with(
                new EnvironmentVariables("APP_NAME", ""),
                new SystemProperties("project.name", ""),
                new SystemProperties("spring.application.name", "aaa")
            )
            .execute(() -> {
                String result = EnvUtils.getAppName();
                Assertions.assertEquals("aaa", result);
            });
    }
}
----



// ----------------------------- 注释


[source,java]
----

----



[source,java]
----
when(userDao.queryUserInfo(any()))
        .thenReturn("mockReturnForFirstCall")       // 第一次调用的模拟返回
        .thenReturn("mockReturnForFistSecondCall"); // 第二次调用的模拟返回

when(userDao.queryUserInfo(any()))
        .thenReturn("mockReturnForFirstCall", "mockReturnForFistSecondCall")

when(someMock.someMethod())
    .thenAnswer(new Answer() {
    private int count = 0;

    public Object answer(InvocationOnMock invocation) {
        if (count++ == 1)}{
            return 1;
        }
        return 2;
    });

doReturn(null).when(rulerService)
            .queryPunishRecordPreCheck(any());
doNothing()
            .when(api)
            .checkSrcEventColumn(any(), any(), any());


verify(
    myObject,
    times(n)        // never()/times(n)/atLeastOnce()/astLeast(n)/atMost(n)/only()
)
    .someMethod();


// 校验参数  @Captor
ArgumentCaptor<Person> argument = ArgumentCaptor.forClass(Person.class);
verify(mock)
    .doSomething(argument.capture());
assertEquals("John", argument.getValue().getName());

org.springframework.test.util.ReflectionTestUtils.setField(
    api,
    "dictEventMappingDao",
    dictEventMappingDao
);
----


## powermock

传言powermock 影响测试覆盖率的统计，我实际使用下来没有遇到，gpt给的方式是加入 `@PowerMockIgnore("org.jacoco.agent.rt.*")` 防止powermock 增强jacoco导致统计问题

[source,java]
----
@RunWith(PowerMockRunner.class)
@PrepareForTest(Aaa.class,Bbb.class)
@PowerMockIgnore("org.jacoco.agent.rt.*")                  //  防止powermock 增强jacoco导致统计问题
@SuppressStaticInitializationFor("your.package.XxxClass")  // SuppressStaticInitializationFor注解可以解决mock过程中这些类加载的错误问题
public class DemoTest{

}
----
