



## 使用 slf4j+logback


### API桥接
针对依赖的jar包中有使用 log4j1.x, log4j2.x, acl, jul 的情形，将相关API的调用 转到 slf4j 的接口上。
自身的工程源码中 应仅仅面向slf4j-api 编程，故其他日志框架的二方包应该谁在为runtime

* 应该使用
** ✅ org.slf4j:jul-to-slf4j:*:*:runtime
** ✅ org.slf4j:jcl-over-slf4j:*:*:runtime  or spring-jcl  ： ❓❓❓ 注意：两者互斥，只选择其一即可，建议选择后者。
** ✅ org.slf4j:log4j-over-slf4j:*:*:runtime
** ✅ org.apache.logging.log4j:log4j-to-slf4j  (log4j 2.x)

### API

* 应该使用
** ✅ org.slf4j:slf4j-api

### 实现桥接
slf4j api 内部将日志输出转为调用其他日志实现框架。

* 应该使用
** ✅ ch.qos.logback:logback-classic

* 禁止使用
** ❌ org.slf4j:slf4j-jdk14
** ❌ org.slf4j:slf4j-jcl
** ❌ org.slf4j:slf4j-nop
** ❌ org.slf4j:slf4j-simple
** ❌ org.slf4j:slf4j-log4j12
** ❌ org.slf4j:slf4j-reload4j

### 实现
* 应该使用
** ✅ ch.qos.logback:logback-core
** ✅ ch.qos.logback:logback-classic

* 禁用
** ❌ log4j:log4j
** ❌ org.apache.logging.log4j:log4j-core
** ❌ commons-logging:commons-logging
** ❌ ch.qos.reload4j:reload4j



## jul 相关配置

logback.xml 配置

[source,xml]
----
<configuration>
    <contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator">
        <resetJUL>true</resetJUL>
    </contextListener>
</configuration>
----


install : 配置的方式 （推荐）

logging.properties 文件示例

[source,java]
----
handlers=org.slf4j.bridge.SLF4JBridgeHandler
----

install : 编程的方式


有的 JDK 使用 JVM 属性 `java.util.logging.config.file` 获取对应的 logging.properties 的值，但该值只是是 FileSystem 的（通过 FileInputStream 读取）。
不能是jar包里的。 如果没配置则默认读取  `${JAVA_HOME}/conf/logging.properties`。
可以编程 `LogManager.readConfiguration(xxxInputStream);` 加载配置。


[source,java]
----
static {
    SLF4JBridgeHandler.removeHandlersForRootLogger();
    SLF4JBridgeHandler.install();
}
----

## NDC
class `org.slf4j.NDC` 在 以下 maven 依赖中。

[source,xml]
----
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-ext</artifactId>
  <version>1.7.34</version>
</dependency>
----


## binder


### slf4j 1.x
参考： link:https://www.slf4j.org/faq.html#slf4j_compatible[Implementing the SLF4J API]

所谓的静态绑定，是指 slf4j 1.x 会将上述3个 class 字节码
从jar包中  link:https://github.com/qos-ch/slf4j/blob/v_1.7.36/slf4j-api/pom.xml#L30[排除],
然后由各个 日志框架二方包桥接器（ slf4j-jcl, slf4j-noop） 、日志框架二方包（比如 logback）等实现。

* link:https://github.com/qos-ch/slf4j/blob/v_1.7.36/slf4j-api/src/main/java/org/slf4j/impl/StaticLoggerBinder.java[org.slf4j.impl.StaticLoggerBinder]

org.slf4j.LoggerFactory 内部有 先检查 classpath 下 是否有多个 `org.slf4j.impl.StaticLoggerBinder` class，并 WARNNING， 然后使用第一个。
注意，关于如何定义第一个，并不能依赖文件系统上 jar 包名字的自然顺序的。


* link:https://github.com/qos-ch/slf4j/blob/v_1.7.36/slf4j-api/src/main/java/org/slf4j/impl/StaticMDCBinder.java[org.slf4j.impl.StaticMDCBinder]

`org.slf4j.MDC` 负责调用 `org.slf4j.impl.StaticMDCBinder` ，其接使用 发现的第一个类，这里并没有多个实现告警。

* link:https://github.com/qos-ch/slf4j/blob/v_1.7.36/slf4j-api/src/main/java/org/slf4j/impl/StaticMarkerBinder.java[org.slf4j.impl.StaticMarkerBinder]

`org.slf4j.MarkerFactory` 负责滴啊用 `org.slf4j.impl.StaticMarkerBinder` ，也是直接使用第一个类，不会多实现告警。

而 slf4j 官方的代码中，只有 以下类有调用 `org.slf4j.MarkerFactory` ：

** slf4j-ext : org/slf4j/ext/XLogge
** slf4j-ext : org/slf4j/cal10n/LocLogger
** log4j-over-slf4j : org.apache.log4j.Category

link:https://github.com/logfellow/logstash-logback-encoder[logstash-logback-encoder] 有使用 Marker 类，但也是通过自己的
link:https://github.com/logfellow/logstash-logback-encoder/blob/logstash-logback-encoder-7.4/src/main/java/net/logstash/logback/argument/StructuredArguments.java[StructuredArguments] 创建的，并没有使用到 MarkerFactory/StaticMarkerBinder.







