



## 使用 slf4j+logback


### API桥接
针对依赖的jar包中有使用 log4j1.x, log4j2.x, acl, jul 的情形，将相关API的调用 转到 slf4j 的接口上。
自身的工程源码中 应仅仅面向slf4j-api 编程，故其他日志框架的二方包应该谁在为runtime

* 应该使用
** ✅ org.slf4j:jul-to-slf4j:*:*:runtime
** ✅ org.slf4j:jcl-over-slf4j:*:*:runtime
** ✅ org.slf4j:log4j-over-slf4j:*:*:runtime
** ✅ org.apache.logging.log4j:log4j-to-slf4j  (log4j 2.x)

### API

* 应该使用
** ✅ org.slf4j:slf4j-api

### 实现桥接
slf4j api 内部将日志输出转为调用其他日志实现框架。

* 应该使用
** ✅ ch.qos.logback:logback-classic

* 禁止使用
** ❌ org.slf4j:slf4j-jdk14
** ❌ org.slf4j:slf4j-jcl
** ❌ org.slf4j:slf4j-nop
** ❌ org.slf4j:slf4j-simple
** ❌ org.slf4j:slf4j-log4j12
** ❌ org.slf4j:slf4j-reload4j

### 实现
* 应该使用
** ✅ ch.qos.logback:logback-core
** ✅ ch.qos.logback:logback-classic

* 禁用
** ❌ log4j:log4j
** ❌ org.apache.logging.log4j:log4j-core
** ❌ commons-logging:commons-logging
** ❌ ch.qos.reload4j:reload4j



## jul 相关配置

logback.xml 配置

[source,xml]
----
<configuration>
    <contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator">
        <resetJUL>true</resetJUL>
    </contextListener>
</configuration>
----


install : 配置的方式 （推荐）

logging.properties 文件示例

[source,java]
----
handlers=org.slf4j.bridge.SLF4JBridgeHandler
----

install : 编程的方式


有的 JDK 使用 JVM 属性 `java.util.logging.config.file` 获取对应的 logging.properties 的值，但该值只是是 FileSystem 的（通过 FileInputStream 读取）。
不能是jar包里的。 如果没配置则默认读取  `${JAVA_HOME}/conf/logging.properties`。
可以编程 `LogManager.readConfiguration(xxxInputStream);` 加载配置。


[source,java]
----
static {
    SLF4JBridgeHandler.removeHandlersForRootLogger();
    SLF4JBridgeHandler.install();
}
----

## NDC
class `org.slf4j.NDC` 在 以下 maven 依赖中。

[source,xml]
----
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-ext</artifactId>
  <version>1.7.34</version>
</dependency>
----




