
## Jacskon 启用序列化白名单

### 使用 Jackson 注解设置输出格式

先了解 jackson 注解 `@JsonTypeInfo` 不同配置时，输出的 json 的格式。

.Aaa.java
[source,java]
----
package me.test.first.spring.boot.test.json.a;
public interface Aaa {
}
----

.A10.java
[source,java]
----
package me.test.first.spring.boot.test.json.b;
import me.test.first.spring.boot.test.json.a.Aaa;

public class A10 implements Aaa{
    private String name;
    // ... getter && setter
}
----

.A11.java
[source,java]
----
package me.test.first.spring.boot.test.json.c;
import com.alibaba.fastjson.JSONObject;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import me.test.first.spring.boot.test.json.b.A10;

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY)
public class A11 extends A10 {
    private Integer age;
    // ... getter && setter
}
----

.Test
[source,java]
----
@Test
public void test() {
    ObjectMapper objectMapper = JsonMapper.builder()
            .serializationInclusion(NON_NULL)
            .build();
    A11 a11 = new A11();
    a11.setName("zhang3");
    a11.setAge(38);
    String jsonStr = objectMapper.writeValueAsString(a11);
    System.out.println(jsonStr);
}
----


## JsonTypeInfo.Id
- JsonTypeInfo.Id.NONE : 不输出类名
- JsonTypeInfo.Id.CLASS : 输出完整类型，比如 : `me.test.first.spring.boot.test.json.c.A11`
- JsonTypeInfo.Id.MINIMAL_CLASS : 不输出package，比如 : `.A11`
- JsonTypeInfo.Id.NAME : 只输出类名，比如 : `A11`


.JsonTypeInfo不同配置输出示例
[,cols="1,1,1"]
|===
|JsonTypeInfo.Id |JsonTypeInfo.As | json

|NONE
|*
a|
[source,json]
----
{
  "name": "zhang3",
  "age": 38
}
----

|CLASS
|PROPERTY
a|
[source,json]
----
{
  "@class": "me.test.first.spring.boot.test.json.c.A11",
  "name": "zhang3",
  "age": 38
}
----

|CLASS
|WRAPPER_ARRAY
a|
[source,json]
----
[
  "me.test.first.spring.boot.test.json.c.A11",
  {
    "name": "zhang3",
    "age": 38
  }
]
----


|CLASS
|WRAPPER_OBJECT
a|
[source,json]
----
{
  "me.test.first.spring.boot.test.json.c.A11": {
    "name": "zhang3",
    "age": 38
  }
}
----

|MINIMAL_CLASS
|PROPERTY
a|
[source,json]
----
{
  "@c": ".A11",
  "name": "zhang3",
  "age": 38
}
----

|MINIMAL_CLASS
|WRAPPER_ARRAY
a|
[source,json]
----
[
  ".A11",
  {
    "name": "zhang3",
    "age": 38
  }
]
----

|MINIMAL_CLASS
|WRAPPER_OBJECT
a|
[source,json]
----
{
  ".A11": {
    "name": "zhang3",
    "age": 38
  }
}
----

|NAME
|PROPERTY
a|
[source,json]
----
{
  "@type": "A11",
  "name": "zhang3",
  "age": 38
}
----

|NAME
|WRAPPER_ARRAY
a|
[source,json]
----
[
  "A11",
  {
    "name": "zhang3",
    "age": 38
  }
]
----

|NAME
|WRAPPER_OBJECT
a|
[source,json]
----
{
  "A11": {
    "name": "zhang3",
    "age": 38
  }
}
----

|===


### Jackson 启用 全局反序列化白名单

[source,java]
----
    @Test
    public void testWhiteList() {
        ObjectMapper objectMapper = JsonMapper.builder()
                .serializationInclusion(NON_NULL)
                .build();

        PolymorphicTypeValidator validator = BasicPolymorphicTypeValidator.builder()
                // 注意：以下 任意启用 allowIfBaseType 或者 allowIfSubType 都OK。
                // 但仅仅启用 allowIfBaseType 时，不能配置成 "me.test.first.spring.boot.test.json.b" : 猜想是根据最顶层的接口来检查的 而检测失败。
                //.allowIfBaseType("me.test.first.spring.boot.test.json.a")
                .allowIfSubType("me.test.first.spring.boot.test.json.c")
                .build();
        objectMapper.activateDefaultTyping(validator, ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);

        String jsonStr = "{\"@class\":\"me.test.first.spring.boot.test.json.c.A11\",\"name\":\"zhang3\",\"age\":38}";

        Aaa aaa = objectMapper.readValue(jsonStr, Aaa.class);

        Assertions.assertInstanceOf(A11.class, aaa);
        A11 newA11 = (A11) aaa;
        Assertions.assertEquals("zhang3", newA11.getName());
        Assertions.assertEquals(38, newA11.getAge());
    }
----

注意: 如果使用 `objectMapper.activateDefaultTyping(PolymorphicTypeValidator)`, 默认使用的是 `JsonTypeInfo.Id.CLASS`, `JsonTypeInfo.As.WRAPPER_ARRAY`

如果此时 A11 上注解配置的 不是 该值，就会造成格式不匹配，进而JSON反序列化异常。

故在限定的使用场景下，需要统一使用一种 `JsonTypeInfo.Id.`,`JsonTypeInfo.As` 配置。
如果既有class上的没有JsonTypeInfo注解，或者主键上与该全局白名单解析配置的不一致，则需要使用 `objectMapper.addMixIn(Class,Classs)` 来统一。


### Jackson 关闭 全局反序列化白名单

[source,java]
----
objectMapper.deactivateDefaultTyping();
----
