

## 参考


* link:https://github.com/async-profiler/async-profiler[async-profiler]
  最新版本的命令是 `asprof`
** https://github.com/async-profiler/async-profiler/tree/v2.9[2.9],
   2.9 以及以前的命令是 `profiler.sh`

* 《link:https://zhuanlan.zhihu.com/p/640264280[开源 Java 性能分析器比较：VisualVM、JMC 和 async-profiler]》
* 《link:https://www.oracle.com/java/technologies/jdk-mission-control.html[JDK Mission Control]》



## 运行

在docker中运行验证。

[source,shell]
----
docker run --rm -it \
-v ~/Downloads/async-profiler-2.9-linux-musl-x64:/opt/async-profiler \
docker.io/library/eclipse-temurin:8-jdk-alpine sh
----

## 原理
* cpu profiler实现一般有两种方案：（1）Sampling，采样（2）Instrumentation，埋点；采样对性能损耗较小但没那么准确，埋点（类似AOP）精准但性能影响大
* Sampling采样只能在Safe Ponit处采样，会导致统计结果偏差，也就是开头说的Safepoint bias problem，例如某些方法执行时间短，但执行频率高，正真占用了cpu，这部分如果Sampling的采样频率不能足够小，可能就采样不到，但采样频率过高又会影响性能，这就是一般的基于采样的cpu profiler的缺点
* async-profiler是基于采样实现的，但它又没有Safepoint bias problem，它是通过一种叫做AsyncGetCallTrace的方式来采样，这种采样不需要在安全点处采样，但这个函数不是那么容易就调用到的，需要使用一些技巧（黑科技）的方式来获取



## 能力

### CPU profiling
### ALLOCATION profiling


### Wall-clock profiling
### Java method profiling


## demo

## 启动挂载 mode

## 先运行，后 attach

## 4.0
[source,shell]
----
wget https://github.com/async-profiler/async-profiler/releases/download/v4.0/async-profiler-4.0-linux-x64.tar.gz
tar zxvf async-profiler-4.0-linux-x64.tar.gz
cd async-profiler-4.0-linux-x64
./bin/asprof list "${JAVA_PID}"
Basic events:
  cpu
  alloc
  nativemem      # ⭕️ 4.0 新增
  lock
  wall
  itimer
  ctimer
Java method calls:
  ClassName.methodName
Perf events:
  cpu-clock
  page-faults
  context-switches
  cycles
  instructions
  cache-references
  cache-misses
  branch-instructions
  branch-misses
  bus-cycles
  L1-dcache-load-misses
  LLC-load-misses
  dTLB-load-misses
  rNNN
  pmu/event-descriptor/
  mem:breakpoint
  trace:tracepoint
  kprobe:func
  uprobe:path

./bin/asprof -d 60 -e nativemem,alloc -f /home/admin/logs/async-profile-%t.$(hostname).%p.jfr "${JAVA_PID}"

----
## 3.0
[source,shell]
----
wget https://github.com/async-profiler/async-profiler/releases/download/v3.0/async-profiler-3.0-linux-x64.tar.gz
tar zxvf async-profiler-3.0-linux-x64.tar.gz
cd async-profiler-3.0-linux-x64
./bin/asprof list "${JAVA_PID}"
Basic events:
  cpu
  alloc
  lock
  wall
  itimer
  ctimer
Java method calls:
  ClassName.methodName
Perf events:
  page-faults
  context-switches
  cycles
  instructions
  cache-references
  cache-misses
  branch-instructions
  branch-misses
  bus-cycles
  L1-dcache-load-misses
  LLC-load-misses
  dTLB-load-misses
  rNNN
  pmu/event-descriptor/
  mem:breakpoint
  trace:tracepoint
  kprobe:func
  uprobe:path

----


## 2.9
[source,shell]
----
wget https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.9/async-profiler-2.9-linux-x64.tar.gz
tar zxvf async-profiler-2.9-linux-x64.tar.gz
cd async-profiler-2.9-linux-x64
./profiler.sh start 209919   # 默认是 -e cpu -i 10ms
./profiler.sh status 209919
./profiler.sh list  209919   # 查看支持的event列表
Basic events:
  cpu
  alloc
  lock
  wall
  itimer
Java method calls:
  ClassName.methodName
Perf events:
  page-faults
  context-switches
  cycles
  instructions
  cache-references
  cache-misses
  branch-instructions
  branch-misses
  bus-cycles
  L1-dcache-load-misses
  LLC-load-misses
  dTLB-load-misses
  rNNN
  pmu/event-descriptor/
  mem:breakpoint
  trace:tracepoint
  kprobe:func
  uprobe:path

./profiler.sh dump 209919    # 不停止 profiler, 并dump输出到控制台

$./profiler.sh meminfo 209919
Call trace storage:   10244 KB
      Dictionaries:      72 KB
        Code cache:   15417 KB
------------------------------
             Total:   25733 KB

./profiler.sh stop 209919
----

dump 示例输出

[source,plain]
----
--- Execution profile ---
Total samples       : 4250
unknown_Java        : 116 (2.73%)
not_walkable_Java   : 1 (0.02%)
deoptimization      : 12 (0.28%)

--- 2837487777 ns (6.61%), 281 samples
  [ 0] __lock_text_start_[k]
  [ 1] __balance_callback_[k]
  [ 2] __schedule_[k]
  [ 3] schedule_[k]
  [ 4] futex_wait_queue_me_[k]
  [ 5] futex_wait_[k]
  [ 6] do_futex_[k]
  [ 7] sys_futex_[k]
  [ 8] do_syscall_64_[k]
  [ 9] entry_SYSCALL_64_after_swapgs_[k]
  [10] __pthread_cond_timedwait
  [11] Unsafe_Park
  [12] jdk.internal.misc.Unsafe.park0
  [13] jdk.internal.misc.Unsafe$1.park0
  [14] com.alibaba.wisp.engine.WispScheduler$Worker.doParkOrPolling
  [15] com.alibaba.wisp.engine.WispScheduler$Worker.runCarrier
  [16] com.alibaba.wisp.engine.WispScheduler$Worker.run
  [17] java.lang.Thread.run

...

         ns  percent  samples  top
  ----------  -------  -------  ---
 17710015168   15.68%     1750  __lock_text_start_[k]
  3996146092    3.54%      395  __pthread_cond_timedwait
  3233578945    2.86%      320  java.dyn.CoroutineSupport.switchTo
  3124501398    2.77%      309  do_syscall_64_[k]
  3042679989    2.69%      301  com.alibaba.wisp.engine.WispTask.unparkInternal
  2536975599    2.25%      251  com.alibaba.wisp.engine.WispScheduler$Worker.runCarrier
  2516678408    2.23%      249  java.util.concurrent.ConcurrentLinkedQueue.poll
  1951119051    1.73%      193  com.alibaba.wisp.engine.TimeOut$TimerManager$Queue.siftUp
  1798663163    1.59%      178  Parker::park(bool, long)
  1547706055    1.37%      153  com.alibaba.wisp.engine.TimeOut$TimerManager$Queue.siftDown
  1415044550    1.25%      140  java.dyn.CoroutineSupport.unsafeSymmetricYieldTo
  1325320960    1.17%      131  __lll_unlock_wake
  1142876902    1.01%      113  java.util.concurrent.ConcurrentLinkedQueue.peek
  1141942781    1.01%      113  Unsafe_Park
   993140819    0.88%       98  futex_wake_[k]
   992616460    0.88%       98  finish_task_switch_[k]
   961694292    0.85%       95  __audit_syscall_exit_[k]
   940236195    0.83%       93  __vdso_clock_gettime
   939782101    0.83%       93  jdk.internal.misc.Unsafe.park0
   890002202    0.79%       88  java.util.concurrent.ConcurrentLinkedQueue.offer
   876349963    0.78%       86  /home/admin/cmms/lib/libcmmsclientjni_x86_64_v0.2.13_1704889135953.so
   859342327    0.76%       85  java_lang_Thread::set_thread_status(oopDesc*, java_lang_Thread::ThreadStatus)
   839843307    0.74%       83  trace_sys_enter_hit?[ali_professor]_[k]
   839219517    0.74%       83  clock_gettime
   798857350    0.71%       79  _raw_spin_lock_[k]
   778254749    0.69%       77  Monitor::lock_without_safepoint_check()
----








[source,shell]
----
JAVA_PID=$(ps aux|grep java | grep org.apache.catalina.startup.Bootstrap|awk '{print $2}')
echo ${JAVA_PID}

# 采集60秒 的CPU事件，并输出成HTML文件
./profiler.sh -d 60 -e cpu -f /tmp/profiler.html "${JAVA_PID}"

./profiler.sh -d 60 -e alloc "${JAVA_PID}"

./profiler.sh -d 60 -e cpu -e alloc -f /tmp/profiler.html "${JAVA_PID}"

./profiler.sh -d 180 -e cpu,alloc,lock -f /home/admin/logs/async-profile-%t.$(hostname).%p.jfr "${JAVA_PID}"
# 一次性以 wall-clock 方式采集，注意：不能同时使用 cpu 等event 类型
./profiler.sh -d 180 -e wall -t -f /home/admin/logs/async-profile-%t.$(hostname).%p.jfr "${JAVA_PID}"



# continuous profiling : 持续 profiler,
# 每记录10分钟输出一次，同时记录多种事件，输入到JFR文件中。
# 注意：只有 JFR 文件格式才支持同时记录多种事件
./profiler.sh --loop 10m  -e cpu,alloc,lock -f /tmp/profile-$(hostname)-%p-%t.jfr "${JAVA_PID}"



----
