


[source,shell]
----
# 列出 通过 `-X` 设置的选项
java -X

# 列出通过 `-XX:` 设置非标选项
java -XX:+PrintFlagsFinal > /tmp/jvm_options.txt
grep LogCompilation /tmp/jvm_options.txt        # 不显示
# 检查特定选项是否支持
java -XX:+LogCompilation -version


# 列出通过 `-XX:` 设置非标选项，且解锁诊断相关的选项， 比如:   `-XX:+PrintCompilation`
java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal  > /tmp/jvm_options2.txt
grep LogCompilation /tmp/jvm_options2.txt      # 显示
java -XX:+UnlockDiagnosticVMOptions -XX:+LogCompilation -version

# 列出开启 `-XX:+UnlockDiagnosticVMOptions` 后新增的可用选项
diff --unchanged-line-format='' --old-line-format='' --new-line-format='%L'  /tmp/jvm_options.txt /tmp/jvm_options2.txt
grep diagnostic /tmp/jvm_options2.txt

----


## threadlocal


----
public interface TLRestoreFactory {

    /**
     * 线程切换时，该代码在老线程执行，以便获取老线程内的上下文信息。
     *
     * @return
     */
    TLRestore newTLRestore();
}
public interface TLRestore {

    /**
     * 请在线程切换时调用，需要再AutoCloseable 中完整清理工作。
     *
     * @return
     */
    AutoCloseable makeCurrent();
}

----

## 查找线程切换的地方

常见线程切换的地方有：
● 自定义  new Thread 并 start 执行；
● 自定义提交 Runnable 到 java.util.concurrent.Executor 等线程池。
  搜索关键词: `.submit(`
* java.util.concurrent.ScheduledThreadPoolExecutor
  搜索关键词: `.schedule(`, `.scheduleAtFixedRate(`
● logback : ch.qos.logback.classic.AsyncAppender 异步输出日志。
● 使用JDK 的 parallel stream 机制： java.util.stream.BaseStream#parallel
（固定运行在 java.util.concurrent.ForkJoinPool#common 上）
● 使用 rxjava 的 parallel 机制: io.reactivex.rxjava3.core.Flowable#parallel().runOn(Schedulers.computation())
● 使用 project reactor 的 parallel 机制: reactor.core.publisher.Flux#subscribeOn(Schedulers.parallel())
* 回调函数：
** 阿里云SLS: com.aliyun.openservices.aliyun.log.producer.Producer#send, 搜索关键词: `.send(`
* 搜索关键词 `callback` (不区分大小写)
*  `.subscribe(`
* `Listener`
* `.send(`


## 环境变量
* 优先级: _JAVA_OPTIONS > java命令行参数 > JAVA_TOOL_OPTIONS

* _JAVA_OPTIONS
* JAVA_TOOL_OPTIONS : link:https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html[The JAVA_TOOL_OPTIONS Environment Variable]

* JDK_JAVA_OPTIONS
* JDK_JAVAC_OPTIONS

* JAVA_OPTS: apache tomcat 等java程序会使用


== 方法签名



:table-caption: 基本类型对应的符号
[#my-tbl1,cols="1,2"]
.table1 title
|===
|符号 | Java类型

| Z     | boolean
| B     | byte
| C     | char
| S     | short
| I     | int
| J     | long
| F     | float
| D     | double
| L     | 对象引用
|===


如果是 `JJ` 则表示2个 long 类型的参数
如果是 `[I` 则表示 `int[]`


方法描述符格式i
- `()V` : 无参数，返回 void
- `(JI)I` : 参数为 `(long,int)`, 返回int
- `(Ljava/lang/String;)V` : 参数为 String 对象, 返回 void
- `((JILjava/util/List;)D` : 参数为 `(long, int, List)` 对象, 返回 double

