
## Native Memory Tracking (NMT)

* link:https://www.baeldung.com/native-memory-tracking-in-jvm[Native Memory Tracking in JVM]


除了 堆内存（heap），JVM还会额外申请内存用于，最终申请的总内存会超过 `-Xmx` 设置的值。

* class metadata
* application code
* JIT 生成的代码
* 内部数据结构等等


### Metaspace

Metaspace 在JDK1.8 或更早，被称之为 PermGen / Permanent Generation.
Metaspace 保存了 已加载的 class的 元信息，而包含 class对象的实例。
class 对象的实例是保存在 heap 中的

heap 相关大小配置（ `-Xmx` 等）不影响 Metaspace 的大小。

可以使用 `-XX:MetaspaceSize`, `-XX:MaxMetaspaceSize` 来配置 metaspace 的大小。
注意：JDK1.8 以及更早，使用的 开关是 `-XX:PermSize`, `-XX:MaxPermSize`


### Threads

这里是指 thread 运行时堆栈传递的信息。
问：一个jvm最多可创建多少个线程？ 取决于机器还有多少剩余内存，每个线程运行的堆栈深度是多少，堆栈上传参数量的多少等。

通常使用 `-Xss` 来配置线程堆栈大小。


### code cache
java 的 class字节码是平台独立的，而运行时是通过JIT将class字节码翻译成 实际机器上的 CPU 指令。
JIT 在编译后，会将这些 CPU 指令保存在 Code Cache 中。

可以通过  `-XX:InitialCodeCacheSize`, `-XX:ReservedCodeCacheSize` 来配置其大小。

### Garbage Collection
GC 运行时，也需要一些 heap 以外的内存来存储其内部数据结构。


### Symbols

字符串的优化

* link:https://openjdk.org/jeps/254[JEP 254: Compact Strings]
String内部数据从 `char[]` 变成 `byte[]` 并增加一个标志位类表示使用哪种，可减少内存，且String 相关方法等更快了。

* link:https://openjdk.org/jeps/192[JEP 192: String Deduplication in G1] :
对于运行时动态创建出的相同的 String 对象，在 G1 GC 时，保持 String 对象不变，但替换内部的 `char[]` , `byte[]`。
只有对长期保存的 String 对象去重才有意义。
开关项: `UseStringDeduplication` : bool, 开启String去重
** `PrintStringDeduplicationStatistics`: bool , 打印详细的去重统计信息
** `StringDeduplicationAgeThreshold` : 达到这个年龄的String对象被认为是去重的候选对象


### Native Byte Buffers

* 通过 JNI + malloc 来向操作系统直接申请内存
* 通过 java.nio.ByteBuffer#allocateDirect 来向操作系统直接申请内存

### Additional Tuning Flags


[source,shell]
----
java -XX:+PrintFlagsFinal -version | grep <concept>
-XX:NativeMemoryTracking=off|sumary|detail

# 示例输出
Native Memory Tracking:
Total: reserved=1731124KB, committed=448152KB
Java Heap (reserved=307200KB, committed=307200KB)
          (mmap: reserved=307200KB, committed=307200KB)
Class (reserved=1091407KB, committed=45815KB)
      (classes #6566)
      (malloc=10063KB #8519)
      (mmap: reserved=1081344KB, committed=35752KB)
Thread (reserved=37018KB, committed=37018KB)
       (thread #37)
       (stack: reserved=36864KB, committed=36864KB)
       (malloc=112KB #190)
       (arena=42KB #72)
Code (reserved=251549KB, committed=14169KB)
     (malloc=1949KB #3424)
     (mmap: reserved=249600KB, committed=12220KB)
GC (reserved=61771KB, committed=61771KB)
   (malloc=17603KB #4501)
   (mmap: reserved=44168KB, committed=44168KB)
Symbol (reserved=10148KB, committed=10148KB)
       (malloc=7295KB #66194)
       (arena=2853KB #1)

# 查看给你个java进程的 native_memory
jps -l
jcmd <pid> VM.native_memory
jcmd <pid> VM.native_memory baseline
jcmd <pid> VM.native_memory summary.diff

----

