



## /dev/random

* link:https://www.baeldung.com/java-security-egd[The java.security.egd JVM Option]
* link:https://metebalci.com/blog/everything-about-javas-securerandom/[Everything about Java's SecureRandom]
* link:https://docs.oracle.com/en/java/javase/11/security/oracle-providers.html#GUID-BC92B7F1-D15C-432A-B725-9BBA9FEF61DB[SecureRandom Implementations]

* java.security.SecureRandom
* sun.security.provider.SunEntries
如果不是对 随机值 要求那么高的情况下，可以使用 `org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16)`
来替代 `UUID.randomUUID().toString()`

* 替代方案1 :
** link:https://github.com/ulid/spec[ulid]
** link:https://github.com/azam/ulidj?tab=readme-ov-file[ulidj]
** link:https://github.com/f4b6a3/uuid-creator[uuid-creator]
** link:https://github.com/cowtowncoder/java-uuid-generator[Java Uuid Generator (JUG)]



```shell
# /dev/random  # 阻塞
# /dev/urandom # 不阻塞
head -c 100 /dev/random  | xxd
head -c 100 /dev/urandom | xxd

cat /proc/sys/kernel/random/poolsiz
cat /proc/sys/kernel/random/entropy_avail

# 可以安装 haveged 来保障 /dev/random 有足够的随机数
#yum install haveged
```

- SUN: NativePRNG            : generateSeed() use /dev/random,  nextBytes() use /dev/urandom
- SUN: NativePRNGBlocking    : generateSeed() use /dev/random,  nextBytes() use /dev/random
- SUN: NativePRNGNonBlocking : generateSeed() use /dev/urandom, nextBytes() use /dev/urandom


[source,java]
----
import java.security.SecureRandom;
public class JavaSecurityEgdTester {
    public static final double NANOSECS = 1000000000.0;

    public static void main(String[] args) {
        SecureRandom secureRandom = new SecureRandom();
        long start = System.nanoTime();
        byte[] randomBytes = new byte[256];
        secureRandom.nextBytes(randomBytes);
        double duration = (System.nanoTime() - start) / NANOSECS;

        System.out.println("java.security.egd = " + System.getProperty("java.security.egd") + " took " + duration + " seconds and used the " + secureRandom.getAlgorithm() + " algorithm");
    }
}
----

run
[source,shell]
----
javac JavaSecurityEgdTester.java
java -cp . JavaSecurityEgdTester                                            # 0.001066818S, NativePRNG
java -cp . -Djava.security.egd=file:/dev/random JavaSecurityEgdTester       # 0.00103736 S, NativePRNG
java -cp . -Djava.security.egd=file:/dev/urandom JavaSecurityEgdTester      # 0.001107522S, NativePRNG
java -cp . -Djava.security.egd=file:/dev/./urandom JavaSecurityEgdTester    # 0.015267088S, DRBG
java -cp . -Djava.security.egd=xxxNotExisted JavaSecurityEgdTester          # 8.011004908S, DRBG


sun.security.provider.AbstractDrbg#generateAlgorithm   # 该接口的3个实现类 CtrDrbg,HashDrbg,HmacDrbg 的实现方式都会 synchronized


# java.security.egd  参考：sun.security.provider.SunEntries#PROP_EGD
# DRBG : Deterministic Random Bit Generator : 确定性随机比特发生器
# PRNG : Pseudo Random Number Generator
# java.security 文件的路径:
# - ${JAVA8_HOME}/jre/lib/security/java.security
# - ${JAVA11_HOME}/conf/security/java.security


# 配置项
securerandom.source=file:/dev/random
                                    # 参考 sun.security.provider.SunEntries#PROP_RNDSOURCE
securerandom.strongAlgorithms=NativePRNGBlocking:SUN,DRBG:SUN
                                    # 参考 java.security.SecureRandom#getInstanceStrong 的源码

securerandom.drbg.config=           # 格式: `${mech_name},${algorithm_name},${strength},${capability},${df}
                                    # 默认值等同于: Hash_DRBG,SHA-256,128,none
                                    # mech_name         : "Hash_DRBG" | "HMAC_DRBG" | "CTR_DRBG"
                                    # algorithm_name    : "SHA-224" | "SHA-512/224" | "SHA-256" | "AES-128" | "AES-192" | "AES-256"
                                    #                      Hash_DRBG 使用 "SHA-*", 默认是 : "SHA-256"
                                    #                      CTR_DRBG  使用 "AES-*", 默认是 : "AES-128"
                                    # strength          :   "112" | "128" （默认） | "192" | "256"
                                    # capability/pr     : Prediction resistance and reseeding request.
                                    #                   : "pr_and_reseed" | "reseed_only" | "none" (默认)
                                    # df                :  只有  CTR_DRBG 才使用，  df=derivation function
                                    #                   : "use_df" (默认) | "no_df"
----

arthas

[source,shell]
----
## NativePRNG, DRBG
# 如果使用 `file:/dev/./urandom` : 会保障 sun.security.provider.NativePRNG.isAvailable() == true,
# 同时因为字符串不匹配，致使 sun.security.provider.SunEntries.DEF_SECURE_RANDOM_ALGO == "DRBG"
ognl @sun.security.provider.SunEntries@DEF_SECURE_RANDOM_ALGO
ognl @sun.security.provider.NativePRNG@isAvailable()


ognl @sun.security.jca.Providers@getProviderList().providers()[0].getService("SecureRandom", "NativePRNG")



# BBS,DRBG,SHA1PRNG,NONCEANDIV,NATIVEPRNGBLOCKING,NATIVEPRNGNONBLOCKING,ECPRNG,NATIVEPRNG,DEFAULT
ognl '@java.security.Security@getAlgorithms("SecureRandom")'
# Hash_DRBG,SHA-256,128,reseed_only
ognl '@java.security.SecureRandom@getInstance("DRBG")'
ognl '@java.security.SecureRandom@getInstance("NativePRNGNonBlocking")'

# sun.security.provider.DRBG
# sun.security.provider.HashDrbg
ognl '
#sr = new java.security.SecureRandom(),
#sr.secureRandomSpi
'

ognl '@sun.security.provider.NativePRNG@INSTANCE'
ognl '@sun.security.provider.NativePRNG@INSTANCE.seedFile.path'
ognl '@sun.security.provider.NativePRNG@INSTANCE.nextIn["in"].path'
----



The JDK has two kinds of SecureRandom implementations.
One is platform-dependent and based on native calls or OS devices such as reading /dev/{u}random on Unix, using the CryptoAPI on Windows,
and using various preconfigured PKCS11 libraries.

The latest releases of Solaris, Linux and Windows already support DRBG, but older releases and embedded systems might not.
The other kind is a pure Java implementation that uses an older SHA1-based RNG implementation, which is not as strong as the algorithms used by approved DRBG mechanisms.


The DRBG mechanisms developed and approved by NIST (as in SP 800-90Ar1) use modern algorithms as strong as SHA-512 and AES-256.
Each of these mechanisms can be configured with different security strengths and features to match user requirements.
Support for these mechanisms is becoming very important in some environments, especially for the U.S. Government.


[source,java]
----
public class Sleep {
    public static void main(String[]args){
        try {
            Thread.sleep(10*60*1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
----


k8s代码合并回弹内发布
支持自定义发布修改元数据获取逻辑
活动反作弊中台sls机器组权限and修复淘同步日志


[source,java]
----
import java.security.SecureRandom;
public class SecureRandomLoadTest {
    public static final double NANOSECS = 1000000000.0;

    public static void main(String[] args) {
        SecureRandom secureRandom = new SecureRandom();
        for(i)
        long start = System.nanoTime();
        byte[] randomBytes = new byte[256];
        secureRandom.nextBytes(randomBytes);
        double duration = (System.nanoTime() - start) / NANOSECS;

        System.out.println("java.security.egd = " + System.getProperty("java.security.egd") + " took " + duration + " seconds and used the " + secureRandom.getAlgorithm() + " algorithm");
    }
}
----


- UUID.randomUUID() 内部使用单例 SecureRandom 对象，高并发时会因 sychronized 降低并发。
  故应该使用
