

* link:https://maven.apache.org/plugins/maven-shade-plugin/plugin-info.html[maven-shade-plugin]
* github link:https://github.com/apache/maven-shade-plugin[apache/maven-shade-plugin]

## 作用
* 可以将传递依赖的 一些jar包按要求 进行shade, 并同时修改其他所有使用的地方，修改的字节码，而源码仍然面向未shaded的接口。
* 可以在 shade 后重新生成 pom.xml，新pom.xml 将 被shade 的二方包进行删除，但同时加入 被shade 二方包的传递依赖，避免部分 shade 时，使用方传递依赖丢失。

## FIXME
* 该如何使用 shade 功能？传递依赖中，哪些应该shaded，哪些不应该shade？
* 是否有独立的classloader 加载机制 类似加载 osgi bundle 的方式，不使用 shade 功能，然后仅仅把要暴露的接口给暴露给使用方？

## 使用场景
## hack某个二方包，按照其接口重新实现某些
比如针对 maven GAV: com.aliyun.oss:aliyun-sdk-oss:3.17.2
重新实现 com.aliyun.oss.OSSClient 入口类（该类在其二方包内部没有被其他类引用），
在特定情形下加入一些对直接读写文件系统的操作。

需要：
* 重新生成一个自己 maven GAV 版本的 `aliyun-sdk-oss` ，比如 `io.github.btpka3:shaded-aliyun-sdk-oss`
  但其中的 `com.aliyun.oss.OSSClient` 被shaded, 比如变成 `shaded.com.aliyun.oss.OSSClient`
* shaded.aliyun-sdk-oss 中 pom.xml 需要自动包含 `aliyun-sdk-oss` 的传递依赖，比如： `io.opentracing:opentracing-api:0.33.0`
* 再开一个 新的 maven GAV: 比如 `io.github.btpka3:proxy-aliyun-sdk-oss`,
  里面重新实现一个  `com.aliyun.oss.OSSClient` 类，可以源码级别直接条件使用 shaded 后的类 `shaded.com.aliyun.oss.OSSClient`。

* FIXME: 为何同一个maven项目组中直接使用 shaded-aliyun-sdk-oss 时，仍然能看到其直接一层的传递依赖 aliyun-sdk-oss ？
* FIXME: 如果我是要 shaded oss 的这个内部类，被原版oss jar包内其他类也引用，
   该如何搞， 用 java.lang.reflect.Proxy#newProxyInstance ?
   如何仅仅shaded 单个类，但其他使用该类的地方不修改？

* 把 `dependency-reduced-pom.xml` 加到 .gitignore 中

[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.5.1</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
            <configuration>
                <promoteTransitiveDependencies>true</promoteTransitiveDependencies>
                <artifactSet>
                    <includes>
                        <include>com.aliyun.oss:aliyun-sdk-oss</include>
                    </includes>
                </artifactSet>
                <relocations>
                    <relocation>
                        <pattern>com.aliyun.oss</pattern>
                        <shadedPattern>shaded.com.aliyun.oss</shadedPattern>
                        <includes>
                            <include>com.aliyun.oss.OSSClient</include>
                        </includes>
                    </relocation>
                </relocations>
            </configuration>
        </execution>
    </executions>
</plugin>
----
