:experimental:

## junit4 to junit5

### 为何升级到 junit5 ?
《link:https://www.baeldung.com/junit-5-migration[Migrating from JUnit 4 to JUnit 5]》

junit4 的限制：
- junit4 所有功能都在一个大 jar 包里，无论相关特性是否使用都会被加载。junit 5 可以按需 加载
- junit4 同一时刻只能运行一个test，junit 5 可以并发运行。
- junit4 无法使用  java 8 及以上版本的特性，junit5 则可以。



=== 如何升级？

=== pom.xml

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <properties>
        <spring-boot.version>2.6.6</spring-boot.version>
        <junit5.version>5.11.0</junit5.version>  <!-- ⭕️ 必须大于等于 5.10.0 -->
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.taobao.pandora</groupId>
            <artifactId>pandora-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- ⭕️: 必须添加该依赖 -->
        <dependency>
            <groupId>com.taobao.pandora</groupId>
            <artifactId>pandora-boot-test-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- ⭕️: 必须添加该依赖 -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!-- BOM import : 越靠前的越优先 -->
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit5.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <classpathDependencyExcludes>
                        <classpathDependencyExclude>org.junit.platform:junit-platform-launcher</classpathDependencyExclude>
                    </classpathDependencyExcludes>
                    <!--
                        注意：该值必须设置为 大于0，否则报错 "Can not load this fake sdk class"
                        参考 surefire 源码 org.apache.maven.plugin.surefire.AbstractSurefireMojo.createStartupConfiguration 关于 isForking 相关逻辑
                        如果 不 fork, 会在maven主线程中运行，并强制使用 org.junit.platform:junit-platform-launcher, 而造成未加载 pandora。
                      -->
                    <forkCount>1</forkCount>
                    <argLine>
                        --illegal-access=permit
                        --add-opens=org.junit.platform.launcher.core/org.junit.platform.launcher.core=ALL-UNNAMED
                        -Denforcer.skip=true
                        -Dautoconfig.skip=true
                        -Dfile.encoding=UTF-8
                        @{argLine}
                    </argLine>
                    <useSystemClassLoader>false</useSystemClassLoader>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <append>true</append>
                </configuration>
                <executions>
                    <execution>
                        <id>pre-unit-test</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <!--Sets the name of the property containing the settings for JaCoCo runtime agent. -->
                            <!--<propertyName>argLine</propertyName>-->
                        </configuration>
                    </execution>
                    <execution>
                        <id>post-unit-test</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <configuration>
                            <excludes>
                                <exclude>**/*.xlsx</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.2.5</version>  <!-- ⭕️ 必须大于等于3.1.2 -->
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.11</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
----

==== 代码改造

// 示例1：最简单demo
:table-caption: 代码改造
[#my-tbl1,cols="1,1,1"]
.table1 title
|===
|action|junit4 | junit5

| import 替换
| `import org.junit.Before;`
| `import org.junit.jupiter.api.BeforeEach;`

| import 替换
| `import org.junit.Test;`
| `import org.junit.jupiter.api.Test;`

| import 替换
| `import org.junit.Assert;`
| `import org.junit.jupiter.api.Assertions;`

| import 替换
| `import org.junit.BeforeClass;`
| `import org.junit.jupiter.api.BeforeAll;`

| import 替换
| `import org.junit.runner.RunWith;`
| `import org.junit.jupiter.api.extension.ExtendWith;`

| import 替换
| `import org.mockito.junit.MockitoJUnitRunner;`
| `import org.mockito.junit.jupiter.MockitoExtension;`

| import 替换
| `import com.taobao.pandora.boot.test.junit4.PandoraBootRunner;`
| `import com.taobao.pandora.boot.test.junit5.PandoraBootExtension;`

| import 替换
| `import static org.junit.Assertions.*;`
| `import static org.junit.jupiter.api.Assertions.*;`

| import 替换
| `import static org.junit.Assertions.a`
| `import static org.junit.jupiter.api.Assertions.a`

| import 替换
| `import junit.framework.Assert;`
| `import org.junit.jupiter.api.Assertions;`

| import 替换
| `import static junit.framework.Assertions.*;`
| `import static org.junit.jupiter.api.Assertions.*;`

| import 替换
| `import org.junit.Ignore;`
| `import org.junit.jupiter.api.Disabled;`

| import 删除
| `import com.taobao.pandora.boot.test.junit4.DelegateTo;`
|

| import 删除
| `import org.apache.tools.ant.types.Assertions;`
|

| import 删除
| `\@RunWith\(PowerMockRunner\.class\)`  # 正则
|

| import 删除
| `\@RunWith\(PowerMockRunner\.class\)`  # 正则
|

| 代码 替换
| `@RunWith(PandoraBootRunner.class)`
| `@ExtendWith(PandoraBootExtension.class)`

| 代码 替换
| `@DelegateTo(MockitoJUnitRunner.class)`
| `@ExtendWith(MockitoExtension.class)`

| 代码 替换
| `@Before\n`  # 正则
| `@BeforeEach`

| 代码 替换
| `@BeforeClass`
| `@BeforeAll`

| 代码 替换
| `Assert\.`  # 正则
| `Assertions.`

| 代码 替换
| `@Ignore`
| `@Disabled`


|===


替换后的检查

[source,shell]
----
# 检查是否有漏替换的
find src/test/java -type f | xargs grep "org.junit." | grep -v "jupiter"
# 检查是否有单测代码是否编译报错
mvn -Dautoconfig.interactive=off -Dautoconfig.skip=true -Derror-prone.doNotBlock=true -Denforcer.skip=true test-compile
# 本地执行单测
mvn -Dautoconfig.interactive=off -Dautoconfig.skip=true -Derror-prone.doNotBlock=true -Denforcer.skip=true clean test
----
