* link:https://prometheus.io/[prometheus]
* micrometer : link:https://micrometer.io/docs/registry/prometheus[prometheus]
* 阿里云: link:https://www.aliyun.com/product/developerservices/prometheus[可观测监控 Prometheus 版]
** aliyun_prometheus_agent_all_targets_num
* link:https://github.com/prometheus/pushgateway/blob/master/README.md[Prometheus Pushgateway]
* link:https://flink.apache.org/2019/03/11/flink-and-prometheus-cloud-native-monitoring-of-streaming-applications/[Flink and Prometheus: Cloud-native monitoring of streaming applications]
*
* github: link:https://github.com/apache/flink-connector-prometheus[apache/flink-connector-prometheus]
  apache flink 的 prometheus 源表，结果表？但目前还是空的。

Prometheus 是一个开源的服务监控系统和时序数据库，


[source,yaml]
----
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
----


## 查询表达式
[source,shell]
----
################### Instant vector selectors
# metrics name 不能是以下关键字: "bool", "on", "ignoring", "group_left", "group_right"
xxx_metrics_name   # 等价于 `{__name__="xxx_metrics_name"}`

# `=` : 字符串完全匹配
# `!=` : 不等于
# 查询当前时间的值
xxx_metrics_name{labal1="value1",label2="value2"}
# 查询5分钟前的值
xxx_metrics_name{labal1="value1",label2="value2"} offset 5
# 查询给定时间点（2021-01-04T07:40:00+00:00）的值
xxx_metrics_name{labal1="value1",label2="value2"} @ 1609746000
# 查询给定时间点（2021-01-04T07:40:00+00:00）5分钟后的值
xxx_metrics_name{labal1="value1",label2="value2"} @ 1609746000 offset 5m
# 查询给定时间点（2021-01-04T07:40:00+00:00）5分钟前的值
xxx_metrics_name{labal1="value1",label2="value2"} offset 5m @ 1609746000

# 查询5分钟前的值的总和
SUM(xxx_metrics_name{labal1="value1",label2="value2"} offset 5m)


# `=~` : 正则匹配。  labal1=~"value1"  等价于 labal1=~"^value1$"
# `!~` : 正则不匹配。
xxx_metrics_name{labal1=~"value1"}
# 使用正则进行多值匹配
xxx_metrics_name{labal1=~"value1|value1|value3"}

################### Range Vector Selectors
# 语法与 Instant vector selectors 相似，但后面增加了一个时间范围（过去多长时间）
xxx_metrics_name{labal1="value1",label2="value2"}[5m]
# 单位:
# "ms" : 毫秒
# "s"  : 秒
# "m"  : 分钟
# "h"  : 小时
# "d"  : 天
# "w"  : 周 （7天）
# "y"  : 年 （365天）

# 示例值：
5h
1h30m
5m
10s
----

## 函数
[source,shell]
----

----






## docker 运行
[source,shell]
----
docker run \
    --rm \
    --name my-prometheus \
    -p 9090:9090 \
    docker.io:prom/prometheus

    # -v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml \

# 然后浏览器访问 http://localhost:9090/ 并用以下 Graph 语句查询
rate(promhttp_metric_handler_requests_total{code="200"}[1m])
----

## HTTP API

[source,shell]
----

# 查看有哪些 prometheus 服务器自身的 metrics
curl -v http://localhost:9090/metrics

# http API
PROMETHEUS_HOST=https://cn-hangzhou.arms.aliyuncs.com:9443/api/v1/prometheus/8ae6858789bbe0b2c8435628deb4e9/1968347570435952/cc595459f560d4b9087013b88b523dc12/cn-hangzhou
PROMETHEUS_HOST=http://localhost:9090

# 查看 有多少种时序数据
curl -v -G ${PROMETHEUS_HOST}/api/v1/series -d 'match[]=up' | jq

# 查看当前的值
curl -v -G ${PROMETHEUS_HOST}/api/v1/query -d query=up | jq

# 查看 label
curl -v -G ${PROMETHEUS_HOST}/api/v1/labels | jq

# 查看 label=scope 的 值
curl -v -G ${PROMETHEUS_HOST}/api/v1/label/scope/values | jq

# 列出服务发现目标信息
curl -v -G ${PROMETHEUS_HOST}/api/v1/targets | jq

# 列出报警规则
curl -v -G ${PROMETHEUS_HOST}/api/v1/rules | jq

curl -v -G ${PROMETHEUS_HOST}/api/v1/alerts | jq

curl -v -G ${PROMETHEUS_HOST}/api/v1/targets/metadata  -d 'match_target={job="prometheus"}'| jq
curl -v -G ${PROMETHEUS_HOST}/api/v1/targets/metadata  -d metric=prometheus_tsdb_lowest_timestamp_seconds| jq

curl -v -G ${PROMETHEUS_HOST}/api/v1/metadata | jq
curl -v -G ${PROMETHEUS_HOST}/api/v1/status/config | jq
curl -v -G ${PROMETHEUS_HOST}/api/v1/status/flags | jq
curl -v -G ${PROMETHEUS_HOST}/api/v1/status/runtimeinfo | jq
curl -v -G ${PROMETHEUS_HOST}/api/v1/status/buildinfo | jq
curl -v -G ${PROMETHEUS_HOST}/api/v1/status/tsdb | jq
curl -v -G ${PROMETHEUS_HOST}/api/v1/status/walreplay | jq






----

## 数据类型
* Counter : 单值，数值，只能增加，或者 reset成0后再开始累加，比如 : qps、 qpm
* Gauge : 数值, 但一定时间范围内可以上下波动，比如1分钟内的 cpu 使用率
* Histogram : 一组指标,
** Count : 数量, 比如 1分钟内的请求数
** Sum: 求和值， 比如 1分钟内的请求RT总和，然后就可以求出分钟级平均RT
** Buckets: 维护多个分桶
* Summary: 与 Histogram 类似，也有一个 count 和一个 sum，但 summary 维护一个分位数（ 比如 TOP99, TOP95？）
* Info: 不修改的文本信息，比如 构建是的 git commit id, 运行时的 jdk 版本号等
* StateSet: 类似开关值(true/false)。比如 系统启动时某个功能是否开启: xxx_enabled: true





## Expression query result formats
link:https://prometheus.io/docs/prometheus/latest/querying/api/#expression-query-result-formats[Expression query result formats]




## 术语
* PromQL : Prometheus Query Language


